### ISSUE TITLE
Create/updated readme.md with updated info

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetWebStack#10]
Be explicit about which versions of Web Stack Runtime are here, and then also update the MVC one to cross-link between these two repos.

**Comment by dougbu** [comment]
Isn't this done?

**Comment by Eilon** [comment]
Done now. This repo was already updated w/ versions, and w/ https://github.com/aspnet/Mvc/commit/3898608035795748f8d933dddae50b72ef2aaa5f we're good to go.
