### ISSUE TITLE
ASP.NET Api wrong `HttpContext.Current.Request.Browser.Browser` get chrome on edge

### ISSUE THREAD

**Issue by WeihanLi** [aspnet/AspNetWebStack#102]
I use `HttpContext.Current.Request.Browser.Browser` to get browser name,but I get "chrome" on edge.

**Comment by dougbu** [comment]
Thank you for your feedback. We're closing this issue as the behaviour discussed is by design.

See http://www.davevoyles.com/2015/01/28/microsofts-spartan-browser-uses-chrome-ua-string/ for a description of why Edge reports itself as Chrome.
