### ISSUE TITLE
Proper way to register WebAPI 2 for IIS

### ISSUE THREAD

**Issue by snekbaev** [aspnet/AspNetWebStack#104]
Hi,

it seems both ways work, yet there is a debate that second one is the correct version:

1) Start.cs
```
var config = new HttpConfiguration();
WebApiConfig.Register(config);
app.UseWebApi(config);
```
2) Global.asax
```
protected override void OnApplicationStart()
{
    base.OnApplicationStart();
    GlobalConfiguration.Configure( WebApiConfig.Register );
}
```
Which one is correct and what's the difference (if any) for an ASP.NET WebAPI 2 application hosted with IIS (Azure)

Thank you!

**Comment by dougbu** [comment]
@snekbaev could you please point us to where this point is debated?

As a partial answer, note the Visual Studio templates for Web API use the second approach.

**Comment by snekbaev** [comment]
@dougbu from notes I made:

http://aspnetwebstack.codeplex.com/workitem/2091 (see @kichalla)
https://stackoverflow.com/questions/30610064/relationship-between-webapi-webhost-and-owin
https://stackoverflow.com/questions/33402654/web-api-with-owin-throws-objectdisposedexception-for-httpmessageinvoker

I've been using the first approach for a couple of years at least and it seems to be just fine (local IIS and Azure WebApps). Yet @kichala mentions it is wrong. Then question is how does it run using the first approach, any downsides like performance hit or... Now a bit confused...

Thank you!

**Comment by mkArtakMSFT** [comment]
@snekbaev, in generate we recommend using the second approach you've listed, but both approaches are supported.
