### ISSUE TITLE
IsAjaxRequest throws HttpRequestValidationException

### ISSUE THREAD

**Issue by JJoe2** [aspnet/AspNetWebStack#114]
As described in [this StackOverflow question](https://stackoverflow.com/questions/47847818/how-to-prevent-httprequestvalidationexception-when-calling-isajaxrequest) I am getting an HttpRequestValidationException in a call to `AjaxRequestExtensions.IsAjaxRequest` (MVC 4), with the stack trace below, even though I am selectively allowing HTML.

It seems wrong to me that the `IsAjaxRequest` method should be performing validation, and looking at the implementation of `AjaxRequestExtensions.IsAjaxRequest`:

    return request["X-Requested-With"] == "XMLHttpRequest" || 
        (request.Headers != null && request.Headers["X-Requested-With"] == "XMLHttpRequest")?

should it not be something like:

    return request.Unvalidated["X-Requested-With"] == "XMLHttpRequest" || 
        (request.Unvalidated.Headers != null && request.Unvalidated.Headers["X-Requested-With"] == "XMLHttpRequest")?

My stack trace is:

    System.Web.HttpRequestValidationException (0x80004005): A potentially dangerous Request.Form value was detected from the client (...).
       at System.Web.HttpRequest.ValidateString(String value, String collectionKey, RequestValidationSource requestCollection)
       at System.Web.HttpRequest.ValidateHttpValueCollection(HttpValueCollection collection, RequestValidationSource requestCollection)
       at System.Web.HttpRequest.get_Form()
       at System.Web.HttpRequest.get_Item(String key)
       at System.Web.Mvc.AjaxRequestExtensions.IsAjaxRequest(HttpRequestBase request)
       at MyApp.Application_BeginRequest(Object sender, EventArgs e)
    ...

**Comment by mkArtakMSFT** [comment]
@dougbu, can you please have a look at this?

**Comment by dougbu** [comment]
@JJoe2, @mkArtakMSFT I searched a bit in the current code. We use the validated `HttpRequestBase[...]` and `Headers` in a couple of places in MVC and a few more places in its WebPages dependency. But, we don't use `Unvalidated[...]` or `Unvalidated.Headers` at all. (`Unvalidated` uses are limited to `Unvalidated.Form` and `Unvalidated.QueryString`.)

Disabling validation here may also be too significant a breaking change.

Marking as **super-triage** for further discussion.

**Comment by mkArtakMSFT** [comment]
@JJoe2, it seems you already have a solution about how to achieve what you're trying to. We do not have any plans to modify the current behavior.
