### ISSUE TITLE
Switching Web API from Global.asax to OWIN stops tracing requests to Application Insights

### ISSUE THREAD

**Issue by abatishchev** [aspnet/AspNetWebStack#127]
I'm not quite sure what is the root cause so let me explain the symptoms:

Before:

- ASP.NET Web API 5.2.3
- Global.asax based configuration (basic, from template)
- AI 2.x (2.0 and same for 2.4)
- HTTP requests are getting logged to AI under the Requests category

After:

- ASP.NET Web API 5.2.3
- OWIN based configuration (basic, from template)
- AI 2.x (2.0 and same for 2.4)
- HTTP requests are not getting logged to AI. Only if an exception has occurred and got logged (using IExceptionLogger) then the related request will be logged.

Apparently this is an old, kind of well-known, and long-running issue:

- https://stackoverflow.com/questions/29471811/how-do-i-enable-application-insights-server-telemetry-on-webapi-project-that-use (circa 2015)
https://social.msdn.microsoft.com/Forums/en-US/ccc8de6b-e5bf-4807-83e7-55f42fb33bc6/ai-does-not-log-successful-requests-web-api?forum=ApplicationInsights (2016)
- https://stackoverflow.com/questions/45729187/how-do-i-access-the-owin-request-in-an-appinsights-telemetry-initializer (2017)

Some explaination is given in [this blog](http://blog.marcinbudny.com/2016/04/application-insights-for-owin-based.html) (emphasis is mine):

>StartOperation relies on the CallContext. Thanks to this, you can have some shared piece of data you can access at any point down the call tree. However there are situations, **where the logical sequence of calls is broken in the OWIN pipeline**. This happens when you have a middleware that uses stage markers. One example of such middleware are the ASP.NET Identity and Security packages. This middleware expects to run at a certain point of the System.Web pipeline, which is achieved by subscribing it to corresponding events of the HttpApplication. **Unfortunately, this causes the call tree to be broken** and the data within CallContext is lost. 

And a workaround is available an OSS package ([NuGet](https://www.nuget.org/packages/ApplicationInsights.OwinExtensions/), [GitHub](https://github.com/marcinbudny/applicationinsights-owinextensions)).

My questions are: is this the right repo to open an issue? If yes then can you please take a look? Would love to this this addressed so no 3rd party packages would be necessary,

P.S. I just found another workaround at [ApplicationInsights-dotnet-server#175](https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/175) but didn't have a chance to try it yet.

**Comment by abatishchev** [comment]
Can you please triage this?

**Comment by mkArtakMSFT** [comment]
Hi @abatishchev. Thanks for reporting this issue. We're trying to understand your scenario better and the question is why you're trying to use OWIN pipeline rather than the standard IIS integration?

**Comment by mkArtakMSFT** [comment]
Hi @Tratcher. Is this something to be addressed in the OWIN pipeline, or WebApi should handle this somehow?

**Comment by Tratcher** [comment]
This is an ApplicationInsights issue. The fix should be coordinated between OWIN/Katana and ApplicationInsights. I don't expect any changes in WebApi.

ApplicationInsights says they have fixed at least one issue in 2.5 beta2. https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/175#issuecomment-342538751. @abatishchev have you tried that fix?

**Comment by mkArtakMSFT** [comment]
Thanks @Tratcher
