### ISSUE TITLE
Microsoft.AspNet.WebApi.Client 5.2.4 ReadAsAsync Not Implemented Exception

### ISSUE THREAD

**Issue by KarloCecura** [aspnet/AspNetWebStack#129]
Hi,

I am using Microsoft.AspNet.WebApi.Client 5.2.4 with .NETStandard 2.0, to make a Xamarin.Forms application, but the ReadAsAsync method is throwing this exception:

{System.TypeInitializationException: The type initializer for 'System.Net.Http.FormattingUtilities' threw an exception. ---> System.NotImplementedException: The method or operation is not implemented. at System.Runtime.Serialization.XsdDataContractExporter..ctor () [0x00006] in <3a79d7e511364d8cb549424699c1a7bb>:0 at System.Net.Http.FormattingUtilities..cctor () [0x000e4] in <cfa5c25867be4a27a5f6292084f06ede>:0 --- End of inner exception stack trace --- at System.Net.Http.Formatting.JsonMediaTypeFormatter..ctor () [0x0000b] in <cfa5c25867be4a27a5f6292084f06ede>:0 at System.Net.Http.Formatting.MediaTypeFormatterCollection.CreateDefaultFormatters () [0x00000] in <cfa5c25867be4a27a5f6292084f06ede>:0 at System.Net.Http.Formatting.MediaTypeFormatterCollection..ctor () [0x00000] in <cfa5c25867be4a27a5f6292084f06ede>:0 at System.Net.Http.HttpContentExtensions.getDefaultMediaTypeFormatterCollection () [0x00007] in <cfa5c25867be4a27a5f6292084f06ede>:0 at System.Net.Http.HttpContentExtensions.ReadAsAsync[T] (System.Net.Http.HttpContent content) [0x00000] in <cfa5c25867be4a27a5f6292084f06ede>:0 at ...+<....>d_19.MoveNext () [0x001f6] in C:\Users.... }

Is it a bug or am I doing something wrong?

**Comment by mkArtakMSFT** [comment]
Hi @KarloCecura.
This is a known issue with .Net Standard support in Mono framework. ASP.NET WebStack 3.2.4 release notes do mention this: https://github.com/aspnet/AspNetWebStack/releases/tag/v3.2.4

Also, here is the underlying issue tracking the fix in Mono: https://github.com/mono/mono/issues/6376

Hope this helps.
