### ISSUE TITLE
Scaffolding is broken in 5.2.4 release

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetWebStack#130]
With the release of 5.2.4 of MVC, scaffolding is broken for MVC 5 if customers update their packages until we update VS.

This is a tracking bug to just make sure that the upcoming release will have this fixed.

**Comment by Eilon** [comment]
Just a task, right? Nothing for us to change in Web Stack as far as I understood; ultimately the bug is in Scaffolding.

**Comment by mkArtakMSFT** [comment]
This issue was moved to aspnet/Scaffolding#692
