### ISSUE TITLE
MVC 5.2.30: DropDownListFor binding issue on returning from a POST

### ISSUE THREAD

**Issue by argimenes** [aspnet/AspNetWebStack#138]
When returning to the browser from a POST action, when there has been a model validation error, any drop down lists that share the same options collection from the ViewBag (i.e., List<SelectListItem>) are connected as if by a pointer. For example, if you implement the following lists in Razor, when the browser returns from a model validation error ALL dropdown lists will share the same selected value, because they share the same options collection. The only way I've found around this is to intervene a method that returns a ReadOnlyCollection<SelectListItem>.

This is NOT an issue with GET actions.

Exxample:

```
<div class="row">
<div class="col-md-2">
                                <label>
                                    Deleted?
                                </label>
                                @Html.DropDownListFor(x => x.IsDeleted, ViewBag.YesNos, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.IsDeleted)
                            </div>
                            <div class="col-md-2">
                                <label>
                                    Finalist?
                                </label>
                                @Html.DropDownListFor(x => x.IsFinalist, ViewBag.YesNos, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.IsFinalist)
                            </div>
</div>
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're not making any improvements in this area as this project is in maintenance mode. So only critical blocking and security bugs are considered.
