### ISSUE TITLE
5.2.5-preview1 upgrade scenario broken

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/AspNetWebStack#141]
Expected Behavior:
When you create a Web API site from the templates, then upgrade the versions of your `Microsoft.AspNet.*` packages to 5.2.5-preview1 it should work out of the box.

Actual Behavior:
When you do this you get the message `Application Configuration file "Web.config" is invalid. There was a problem parsing the oldVersion attribute. Input string was not in a correct format.` when you attempt to launch the app. The line it's complaining about looks something like 
`<bindingRedirect oldVersion="1.0.0.0-5.2.5-preview1.0" newVersion="5.2.5-preview1.0" />` , but should be `
        <bindingRedirect oldVersion="1.0.0.0-5.2.5.0" newVersion="5.2.5.0" />`.

This is blocking aspnet/Release#252.

**Comment by dougbu** [comment]
This is a regression compared to the 3.2.4 (MVC 5.2.4) and 3.2.4-preview1 (MVC 5.2.4-preview1) releases.

**Comment by dougbu** [comment]
Fix out for review: http://codeflow/extensions/launcher.html?server=https:%2f%2fdevdiv.visualstudio.com%2f&projectId=2cf24b7e-a928-45ce-a6a9-464648313e80&reviewId=115333&projectshortname=zCodeFlowConfigs

**Comment by dougbu** [comment]
Fixed in [changeset 1691938](http://vstfdevdiv:8080/DevDiv2/DevDiv/_versionControl/changeset/1691938)
