### ISSUE TITLE
Japanese resources for MVC 5.2.4 is broken

### ISSUE THREAD

**Issue by pgrho** [aspnet/AspNetWebStack#143]
Correct: [5.2.4-preview1](https://www.nuget.org/packages/Microsoft.AspNet.Mvc.ja/5.2.4-preview1)
> Microsoft.AspNet.Mvc.ja 5.2.4-preview1
> Microsoft ASP.NET MVC 日本語リソース
> このパッケージには、ASP.NET MVC の 日本語 サテライト アセンブリが含まれています。

Wrong: [5.2.4](https://www.nuget.org/packages/Microsoft.AspNet.Mvc.ja/5.2.4):
> Microsoft.AspNet.Mvc.ja 5.2.4
> !aC0MD!Microsoft ASP.NET MVC {Language} Resources 表©鷗字㌍!
> !lCaXD!This package contains the {Language} satellite assemblies for ASP.NET MVC. 表©鷗字㌍ 表©!

**Comment by Eilon** [comment]
@dougbu - EEP! Looks like pseudo-loc made its way into our satellite resources??

cc @mkArtakMSFT

**Comment by dougbu** [comment]
Yup, looks like we uploaded the *.ja packages from the wrong directory ☹️

**Comment by Eilon** [comment]
I spoke to @mkArtakMSFT and we'll get this fixed for the 5.2.5 release, which should be soon.

In the meantime you can revert back to 5.2.3 if this is blocking you.

**Comment by Eilon** [comment]
@dougbu / @mkArtakMSFT - we should maybe make some adjustments in how we ship this too to prevent errors like this from happening. E.g. have all the stuff to ship be in one folder.

**Comment by mkArtakMSFT** [comment]
Hi @pgrho. We've just released 5.2.5-preview1 release which has the issue fixed.
@Eilon, to prevents things like this from happening again we're now collecting all the packages in an automated manner. The issue which resulted in the wrong packages to be collected has been addressed so we won't hit it again.

**Comment by danroth27** [comment]
@dougbu Should this be closed?

**Comment by mkArtakMSFT** [comment]
It's marked as `Done` already, @danroth27. I'll just wait for confirmation from the customer before closing this.

**Comment by Eilon** [comment]
@mkArtakMSFT you can close the bug when we've fixed it, and we believe we fixed it. If it's still a bug we can re-open.

**Comment by Eilon** [comment]
(Bugs should represent work that is remaining for us, and no work is remaining here.)

**Comment by mkArtakMSFT** [comment]
Fair enough.

**Comment by diontools** [comment]
Unfortunately, this problem has recurred in [v5.2.5](https://www.nuget.org/packages/Microsoft.AspNet.Mvc.ja/5.2.5). [v5.2.5-preview1](https://www.nuget.org/packages/Microsoft.AspNet.Mvc.ja/5.2.5-preview1) has no problem.

**Comment by mkArtakMSFT** [comment]
Hi @diontools. Can you please share a repro project for us to investigate?

**Comment by mkArtakMSFT** [comment]
Actually, @pgrho, can you please create a new bug with the repro steps and link this one from there? Thanks!

**Comment by diontools** [comment]
Hello @mkArtakMSFT. I created a new issue. If it is wrong, would you please correct it?
