### ISSUE TITLE
Support polymorphism for root elements on JSON Web Api endpoints

### ISSUE THREAD

**Issue by madmox** [aspnet/AspNetWebStack#145]
When an `ApiController` can return different implementations of a base class and the `JsonMediaTypeFormatter` is configured to use JSON.Net's automatic type name handling (`TypeNameHandling == TypeNameHandling.Auto`), the `$type` property is not injected in the root element.

**HomeController.cs**
```csharp
public class HomeController : ApiController
{
    private readonly MediaTypeFormatter _formatter = new JsonMediaTypeFormatter()
    {
        SerializerSettings = new JsonSerializerSettings()
        {
            TypeNameHandling = TypeNameHandling.Auto
        }
    };

    public HttpResponseMessage Index()
    {
        BaseClass foo = new ChildClass();
        return this.Request.CreateResponse(HttpStatusCode.OK, foo, this._formatter);
    }
}

public class BaseClass
{
    public string Foo { get; set; } = "foo";
}

public class ChildClass : BaseClass
{
    public string Bar { get; set; } = "bar";
}
```
**JSON**
```javascript
{
    // "$type": "<full type name and assembly of ChildClass>", // this line is missing
    "Bar": "bar",
    "Foo": "foo"
}
```

This unexpected behavior (automatic type name handling works fine for non-root members) is caused by [a limitation in JSON.Net](https://github.com/JamesNK/Newtonsoft.Json/issues/1128), but could be fixed by using `jsonSerializer.Serialize(jsonWriter, value, type);` [here](https://github.com/aspnet/AspNetWebStack/blob/1a987f82d648a95aabed7d35e4c2bee17185c44d/src/System.Net.Http.Formatting/Formatting/BaseJsonMediaTypeFormatter.cs#L433).

**Comment by dougbu** [comment]
@Niladri24dutta suggest you wait a bit. I did not realize we had chosen _not_ to make a similar change to ASP.NET Core Mvc. See aspnet/Mvc#6082

@mkArtakMSFT @danroth27 @Eilon we need to look at this again. Clearing the milestone to remind us.

**Comment by madmox** [comment]
Yep, this is exactly the same issue. I think the reason to not support the feature is understandable (accepting dynamic typing from external clients is risky outside of internal or very controlled APIs). But in this case, it just seems illogical to me to support it at non-root level, where the security issue is the same. Or isn't it?

I understand abandonning support for `TypeNameHandling.Auto` altogether would be a breaking change so the situation is a bit stalled, but I'm very concerned about _things being done the way they should_, so I would be a little bit frustrated if the request was just dropped because of an antinomic security + retrocompatibility paradigm 😆

**Comment by dougbu** [comment]
Thank you for your feedback. We're closing this issue as the behaviour discussed is by design.

**Comment by dougbu** [comment]
FYI if it were possible to disable generating `$type` lower in the serialized JSON, we would.
