### ISSUE TITLE
AsyncLocal / CallContext w/ 32bit appPools and large post bodies

### ISSUE THREAD

**Issue by gunnim** [aspnet/AspNetWebStack#148]
I'm having trouble propogating data using AsyncLocals's or the CallContext (through Trace.CorrelationManager.ActivityId) on 32 bit app pools when sending large post bodies.

My test case is an Asp.Net 4.6.1 visual studio template with Mvc(/Web Api) scaffolding.

In global.asax.cs I Add

    public static AsyncLocal<Guid> ActivityId = new AsyncLocal<Guid>();

	protected void Application_BeginRequest(object sender, EventArgs e)
	{
		var activityId = Guid.NewGuid();
        ActivityId.Value = activityId;
		Trace.CorrelationManager.ActivityId = activityId;
    }

I add an extremely raw logger helper class like so

    public static class Logger
    {
        public static void Log()
        {
            using (var sw = new StreamWriter("C:\\Users\\Public\\Documents\\logfile.txt", true))
            {
                sw.WriteLine($"{DateTime.Now} {WebApiApplication.ActivityId.Value} {Trace.CorrelationManager.ActivityId} {Environment.StackTrace.Substring(0, 500)}");
            }
        }
    }

And finally i add an mvc controller action under the HomeController

	[HttpPost]
	public void Post()
	{
		Logger.Log();
	}

If i then configure my IIS application pool as 32 bit and send a Post request with postman containing 1156+ characters of application/json (or a little over that for text) my activity id and AsyncLocal will be logged as Guid.Empty

This happens on .Net 4.5->4.7.1.
I was unable to reproduce on AspNetCore running the 32bit dotnet.exe.
Also applies to Web Api 2 controllers.

Is there a bug in AspNet related to 32bit AppPools, large post bodies and application contexts?

**Comment by dougbu** [comment]
Does your test scenario work fine when using a 64bit app pool?

**Comment by gunnim** [comment]
Correct

**Comment by dougbu** [comment]
Hi. Thanks for contacting us.

We're closing this issue as there was no much community interest in this ask for quite a while now.
