### ISSUE TITLE
enable asp.net web api session when working with angular5 on localhost

### ISSUE THREAD

**Issue by noah2233** [aspnet/AspNetWebStack#149]
In production mode I have the angular 5 client and the web api on the same site so I have no problem with the session but in development mode my angular 5 is hosted on localhost:4200 which reset the session on each call to a service. I can host the angular 5 and the web api on the same host on development mode but it means I have to do ng build all the time(which will have a big overhead). Any ideas? Should I use the session?

**Comment by Niladri24dutta** [comment]
practically If you are using the session in a REST api then you are loosing the stateless nature of HTTP because you are accessing the session in a REST api. As per my opinion you should try to avoid session if there is any other way around.

**Comment by noah2233** [comment]
I read about the stateless and I am still not sure what it is. Can you please explain?
What do you think I should consider as my alternatives for the session?

**Comment by dougbu** [comment]
Hi. It looks like this is a question about how to use ASP.NET Web API. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the 'asp.net-web-api' [tag](https://stackoverflow.com/questions/tagged/asp.net-web-api).

Separately, we agree with the first response above.
