### ISSUE TITLE
Japanese resources for MVC 5.2.5 is broken

### ISSUE THREAD

**Issue by diontools** [aspnet/AspNetWebStack#156]
This issue is recurrence of #143.

### Functional impact
String in the resource is garbled.

### Minimal repro steps
Nuget package issue.

### Expected result
Display correct string.
[v5.2.5-preview1](https://www.nuget.org/packages/Microsoft.AspNet.Mvc.ja/5.2.5-preview1)
> Microsoft ASP.NET MVC 日本語リソース

### Actual result
Display garbled string.
[v5.2.5](https://www.nuget.org/packages/Microsoft.AspNet.Mvc.ja/5.2.5)
> !aC0MD!Microsoft ASP.NET MVC {Language} Resources 表©鷗字㌍!

**Comment by dougbu** [comment]
Have bumped the versions up to 3.2.6 / 5.2.6 with 3155d174ba and changeset 1698988.

**Comment by dougbu** [comment]
@joeloff addressed the underlying issue in changeset 1698961.

Remaining work includes shoring the build process up to avoid problems with the PLOC packages going forward (including verification of the Japanese packages) and to remove manual steps.

**Comment by dougbu** [comment]
This work is complete. Please upgrade to MVC or Web API 5.2.6. Please note some packages have not yet been indexed in the NuGet gallery.

Example updated package: https://www.nuget.org/packages/Microsoft.AspNet.Mvc/5.2.6

----
I'll file a separate issue about the "remaining work" on automation and verification.

**Comment by diontools** [comment]
Thank you so much. It's working as expected!
