### ISSUE TITLE
AntiForgeryConfig should allow ICryptoSystem configuration

### ISSUE THREAD

**Issue by explunit** [aspnet/AspNetWebStack#157]
AntiForgeryTokenSerializer accepts an `ICryptoSystem` parameter, but the constructor is internal and no configuration of this interface is available on AntiForgeryConfig. This means that MachineKey is the only possible implementation. If this option were exposed on AntiForgeryConfig then developers would be able to provide their own implementation, e.g. a class that wraps the registered OWIN dataprotector.

**Comment by dougbu** [comment]
We have no plans to extend the AntiForgery system in this manner.
