### ISSUE TITLE
Unnecessary whitespace is rendered for non markup content

### ISSUE THREAD

**Issue by SpaceOgre** [aspnet/AspNetWebStack#168]
### Whitespace is rendered for non markup content
When using Razor blocks in a view you get extra whitespaces (newlines, spaces) that should not be there.

### Functional impact
Write code in a not optimal way eg:
```
@if (true)
{
    <text>a</text>}.
```
Or if you are not aware of this bugg then you will get extra whitespaces in your webpage.

### Minimal repro steps
```
@if (true)
{
    <text>a</text>
}.
```

### Expected result
```
a.
```

### Actual result
```
a .
```
The space here is actually a newline but it looks like this in a browser.

### Further technical details
I believe this is the same problem as this issue for Core: https://github.com/aspnet/Razor/issues/485
My hope is that the fixes there could be back ported here.

**Comment by dougbu** [comment]
We've moved this issue is in the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by virenv** [comment]
@dougbu : Any work around for this issue? I am rendering two partial views in my HomePage and I get two new lines introduced between the partial views.
```
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>LMS - ToolsQA</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="http://20tvni1sjxyh352kld2lslvc.wpengine.netdna-cdn.com/wp-content/uploads/2017/05/Favicon-16X16.png" type="image/png">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/ToolsQAStyles/CommonStyles.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <div>
        @*Make the body Composition*@
        @Html.Partial("StandardHeader");
        @Html.Partial("Carousel", Model.CarouselItems);
    </div>
</body>
</html>
```

**Comment by dougbu** [comment]
@virenv we have done no work on this issue and nothing is planned in the near future.

See also https://docs.microsoft.com/en-us/aspnet/mvc/overview/performance/bundling-and-minification

**Comment by Spongman** [comment]
i don't understand how this is marked 'enhancement' when it's clearly a bug.

**Comment by Safirion** [comment]
This bug break display when ` white-space: pre-wrap;` is needed...

Any workaround today ?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're not making any improvements in this area any more as this project is in maintenance mode. Only critical blocking issue with wide impact and security issues are considered.
