### ISSUE TITLE
System.MissingMethodException when calling Microsoft.AspNet.WebApi.Client from Xamarin.iOS 11.12.0.4 / netstandard2.0 library

### ISSUE THREAD

**Issue by hansmbakker** [aspnet/AspNetWebStack#170]
I'm trying to reference `Microsoft.AspNet.WebApi.Client` since I thought [it provides a netstandard2.0 implementation of the System.Net.Http.Formatting extensions](https://github.com/aspnet/AspNetWebStack/issues/169).

I'm using the nuget package from a netstandard2.0 library that is referenced from a Xamarin.iOS 11.12.0.4 app project.

However, when I call something like `await _client.PostAsJsonAsync(uri, profileData);` in the referenced library, I get a `System.MissingMethodException`.

Its message is:

```
System.Threading.Tasks.Task`1<System.Net.Http.HttpResponseMessage> System.Net.Http.HttpClientExtensions.PostAsJsonAsync<!0>(System.Net.Http.HttpClient,System.Uri,!!0)
```

I tried cleaning the project, rebuilding and I tried this [workaround based on binding redirects](https://github.com/aspnet/Hosting/issues/926#issuecomment-276802099) but that unfortunately does not help.

I found https://stackoverflow.com/questions/36090334/httpcontentextensions-readasasync-error which has a similar error but I really do not want to install Microsoft.Net.Http - I would prefer to stick to the System.Net.Http package.

Also I found https://stackoverflow.com/questions/10399324/where-is-httpcontent-readasasync where more people mention that they have issues with this package.

**Comment by dougbu** [comment]
@wind-rider thank you for filing this issue. In order for us to investigate this issue, could you please provide us with a minimal repro project that illustrates the problem, preferably hosted in a GitHub repo?

Debugging would also be easier if you provide the server-side `Exception` as well.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as there's been no response and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
