### ISSUE TITLE
Override ActionFilterAttribute.OnActionExecuting can't returning JsonResult?

### ISSUE THREAD

**Issue by mrhuo** [aspnet/AspNetWebStack#175]
I override ActionFilterAttribute.OnActionExecuting method, and returning an JsonResult like this:
```
public override void OnActionExecuting(ActionExecutingContext filterContext)
{
    filterContext.Result = new JsonResult()
    {
        Data = new RestResult(false, "This is json result."),
        ContentEncoding = Encoding.UTF8,
        ContentType = "application/json",
        JsonRequestBehavior = JsonRequestBehavior.AllowGet
    };
}
```

BUT, I received `{}`, no content? why?
And in other ActionFilterAttribute methods, same result.

**Comment by dougbu** [comment]
@mrhuo thank-you for filing this issue. In order for us to investigate this issue, could you please provide us with a minimal repro project that illustrates the problem, preferably hosted in a GitHub repo?

In particular, what is a `RestResult`? If it's not a POCO object, dictionary, or other relatively-simple class, it's likely incompatible with Json.NET.

**Comment by mrhuo** [comment]
@dougbu I tried a lot of ways to recreate the situation at that time, but never again. I'll close this Issues first. If I find the problem again, I'll mention Issues again. Thank you very much for your reply.
