### ISSUE TITLE
Release notes link in NuGet package is out-of-date

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetWebStack#178]
E.g. go here: https://www.nuget.org/packages/Microsoft.AspNet.WebApi/5.2.6

And there is a link to http://go.microsoft.com/fwlink/?LinkID=403010, which redirects to https://docs.microsoft.com/en-us/aspnet/web-api/overview/releases/whats-new-in-aspnet-web-api-22, which is from 2014.

We should *not* change the FWLink's target because that will make older packages incorrect.

I recommend we change the Release Notes entry to point to this repo: https://github.com/aspnet/AspNetWebStack and then from there people can get whatever info they want.

**Comment by dougbu** [comment]
Just to confirm: @Eilon you mean update the .nuspec files?

**Comment by dougbu** [comment]
Only by overwriting the packages. That would "fix" what shows up on NuGet.org but leave anyone downloading the latest unaffected. (Seems fine because the metadata is primary used on NuGet.org.)

**Comment by Eilon** [comment]
Packages cannot be overwritten on NuGet.org.

**Comment by dougbu** [comment]
@Eilon given
- we're fixing the .nuspec files to include `<repository>` information (#190),
- we don't have a single location for release notes, and
- https://github.com/aspnet/AspNetWebStack#tags-and-releases is the closest thing in this repo to release notes (yeah, not really),

I propose we _remove_ the `<releaseNotes>` elements from our .nuspec files. **Thoughts?**

**Comment by Eilon** [comment]
Yeah remove release notes. If we link to the repo, whatever we post (if anything) can be found here.

**Comment by dougbu** [comment]
FYI the old release note links went different places for MVC, Web.API, &hellip;:
- https://docs.microsoft.com/en-us/aspnet/web-api/overview/releases/whats-new-in-aspnet-web-api-22
- https://docs.microsoft.com/en-us/aspnet/web-pages/overview/releases/whats-new-in-aspnet-web-pages-32
- https://docs.microsoft.com/en-us/aspnet/mvc/overview/releases/whats-new-in-aspnet-mvc-52
- https://blogs.msdn.microsoft.com/webdev/2014/01/20/announcing-the-release-of-asp-net-mvc-5-1-asp-net-web-api-2-1-and-asp-net-web-pages-3-1/

The last one was a fallback for packages (e.g. Microsoft.AspNet.Facebook.nupkg) not covered elsewhere. But, it was even more out-of-date.

**Comment by dougbu** [comment]
Done in [changeset 1728218](http://vstfdevdiv:8080/DevDiv2/DevDiv/_versionControl/changeset/1728218)
