### ISSUE TITLE
Microsoft.AspNet.WebApi.Core (5.2.6) is not compatible with .NET Core 2.1

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetWebStack#179]
_From @NN--- on July 12, 2018 11:5_

After installing nuget Microsoft.AspNet.WebApi.Core I get the following message:
 
```
Package 'Microsoft.AspNet.WebApi.Core 5.2.6' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
```

_Copied from original issue: aspnet/Home#3319_

**Comment by Eilon** [comment]
_From @blowdart on July 12, 2018 12:19_

Ah, wrong package, but I can see why you're confused.

Packages targeting asp.net core being with Microsoft.AspNet*Core*. What you're adding is a package for previous versions of WebApi, and whilst it has Core in its name it's not for the Core platform.

There's no specific WebApi package for ASP.NET Core any more, it's all built into MVC and the .App or .All package.

**Comment by dougbu** [comment]
@Eilon I don't see any action to take here. What are you recommending?

@NN--- the only aspnet/AspNetWebStack package containing ASP.NET Core-compatible assemblies is [Microsoft.AspNet.WebApi.Client](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/.

**Comment by dougbu** [comment]
@NN--- thank you for your feedback. We're closing this issue as the questions asked here have been answered.

As @blowdart said, Microsoft.AspNet.WebApi.Core is not part of ASP.NET Core (Microsoft.AspNetCore.* packages). And, as I said, this repo does produce one compatible package -- [Microsoft.AspNet.WebApi.Client](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/). (But, that one package doesn't seem to be what you're looking for.)

For ASP.NET Core, please see https://github.com/aspnet/Home or, for documentation, https://docs.microsoft.com/en-us/aspnet/index

**Comment by duongphuhiep** [comment]
so basicly, no need to install Microsoft.AspNet.WebApi.Cors package anymore, we should just remove it from project dependencies to get rid of the warning... thanks

**Comment by sapatelbaps** [comment]
I am new to ASP .NET Core and searching to fix this error since two days. Would you please help me what is the work around or how can I fix it - by removing project dependencies? Thnx

**Comment by NN---** [comment]
@sapatelbaps How exactly you created your project ?
If you just use wizards there will be no issue.
As It was mentioned you don't need this package, You need packages starting with "Microsoft.AspNetCore"

**Comment by sapatelbaps** [comment]
@NN--- 
I just created ASP .NET Core web project from Visual Studio 2019 RC Community Edition.
Immediately after creating the project I got this error and looking for solutions but nothing worked out so far! I didn't even open any file of the project just immediately after creating project I got this errors!

**Comment by sapatelbaps** [comment]
Actually, clearing nuget cache from Visual Studio options fixed the issue and now I can build and run the project.

**Comment by AraHaan** [comment]
interesting I got this same issue now; only difference is it is for version ``5.2.7`` not compatible with ``netcoreapp3.1``.

**Comment by saadahmed42** [comment]
Hi - can anyone please tell me what version of Microsoft.AspNet.WebApi.Core is compatible with netcoreapp3.1  .  Also, is there a way to find out this info for any nuget package.

**Comment by Eilon** [comment]
@saadahmed42 I don't think any of them are compatible with netcoreapp3.1 because they are designed to run on .NET Framework and System.Web. For .NET Core 3.1 you need to use ASP.NET Core 3.1: https://docs.microsoft.com/aspnet/core/web-api/?view=aspnetcore-3.1

**Comment by dougbu** [comment]
Agreed @Eilon.
> The only aspnet/AspNetWebStack package containing ASP.NET Core-compatible assemblies is [Microsoft.AspNet.WebApi.Client](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/).
