### ISSUE TITLE
Downgrade Http Version in batch request

### ISSUE THREAD

**Issue by ankitbko** [aspnet/AspNetWebStack#183]
The issue is being discussed over https://github.com/dotnet/corefx/issues/31238

The problem in short is that corefx recently changed default http version to HTTP/2. This means that any existing application which is updated to .net core, the version in each segment of multipart batch request also changed. In my case, I was sending batch request to Dynamics CRM, however due to explicit version check in OData client this was failing. 

I have raised an issue in OData repo as well. We need to discuss with OData team and corefx to find best approach to this. Please have a look at the linked issue in corefx.

**Comment by dougbu** [comment]
@ankitbko it's not clear there's a need for Web API to change here. Are you hitting an error at this layer as well?

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as there's been no response and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
