### ISSUE TITLE
Bug: Rendering a layout of a layout causes lost HttpContext.Current.Session dictionary entries

### ISSUE THREAD

**Issue by dreschner** [aspnet/AspNetWebStack#186]
Hey guys,

I think I discovered a bug in the AspNetWebStack.

We use sitecore and would like to define a global skeleton for all pages for easier handling. Before that, we had to copy the layout several times instead of having one page.

To achive that, one example layout.cshtml looks like this:
[Layout.txt](https://github.com/aspnet/AspNetWebStack/files/2270331/Layout.txt)

and our _skelton.cshtml, which is included in several other layouts, look like this:
[_Skeleton.txt](https://github.com/aspnet/AspNetWebStack/files/2270337/_Skeleton.txt)

We now have an issue with HttpContext in controllers and renderings in the skeleton. For example, the following line `@Html.Sitecore().Rendering(Renderings.Metadata.PageTitle)` starts a sitecore pipeline, in which we set the page title which is rendered in this place then. One of our processors check the HttpContext.Current.Session, if there is a value for the key "FormError". This works like charm as long as the rendering is rendered in the layout.cshtml. When we put it in the skeleton file, the dictionary entry of in the HttpContext.Current.Session isn't there anymore.

I checked the stacktraces and see that the only difference is the call of some WebPageBase methods, which look like they kill the HttpContext somehow. I'm not sure, but especially the PopContext() method looks suspicious to me.

![image](https://user-images.githubusercontent.com/34408442/43838510-d1aa4e94-9b1b-11e8-9378-b5da2ed106ed.png)

Could you have a look at it if it's a bug or desired behavior?

Thanks!

Best reguards

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
