### ISSUE TITLE
NuGet Package : Add `repository` metadata. 

### ISSUE THREAD

**Issue by MaximRouiller** [aspnet/AspNetWebStack#190]
Basically, we can now add a repository metadata on a nuspec file to allow the repository to be surfaced on NuGet. This allows you to have a `projectUrl` as well a repository URL now.

I've talked about it [on Twitter](https://twitter.com/MaximRouiller/status/1030468873945075712) but the most basic things to know is here:

[NuSpec Reference](https://docs.microsoft.com/en-us/nuget/reference/nuspec?WT.mc_id=social-github-marouill#repository)

Reference Implementation in Json .NET
![image](https://user-images.githubusercontent.com/209384/44277447-b1c20f00-a218-11e8-9406-4f1f05879d47.png)

**Comment by MaximRouiller** [comment]
@natemcmaster are you doing the PR or should I?

**Comment by natemcmaster** [comment]
Feel free to send a PR. @Eilon who services this repo and could help bring in the change?

**Comment by MaximRouiller** [comment]
@natemcmaster @Eilon does `https://github.com/aspnet/AspNetWebStack/blob/master/Directory.Build.props` makes sense to you as to where I should add it to have it imported into everything?

**Comment by Eilon** [comment]
@mkArtakMSFT runs this repo, and @dougbu is the main expert.

**Comment by dougbu** [comment]
Feel free to send a PR to change [src/WebApiHelpPage/WebApiHelpPage.nuspec](https://github.com/aspnet/AspNetWebStack/blob/c40bca36f9b9cd690d100107699c3ca91ffeaf22/src/WebApiHelpPage/WebApiHelpPage.nuspec) and [src/WebApiHelpPage/VB/WebApiHelpPage.VB.nuspec](https://github.com/aspnet/AspNetWebStack/blob/c40bca36f9b9cd690d100107699c3ca91ffeaf22/src/WebApiHelpPage/VB/WebApiHelpPage.VB.nuspec). We appreciate the help.

We'll handle the remaining packaging which is in an internal repository.

**Comment by MaximRouiller** [comment]
@dougbu whenever you're ready.

**Comment by dougbu** [comment]
Thanks @MaximRouiller

**Comment by dougbu** [comment]
2109e7e082 takes care of this repository. Remaining work is in internal packages.

**Comment by dougbu** [comment]
Remainder done in [changeset 1728218](http://vstfdevdiv:8080/DevDiv2/DevDiv/_versionControl/changeset/1728218)

**Comment by MaximRouiller** [comment]
@dougbu Thank you so much!

cc @spboyer
