### ISSUE TITLE
How Can I Improve The Speed of Each Action(View Page) when Frist Visit Razor View cshtml  in MVC4 ?

### ISSUE THREAD

**Issue by sgf** [aspnet/AspNetWebStack#191]
i dont know why the RazorViewEngine need so much time to compile the View,
**Each Page need take 2-5 sec when first time visit.**
 Even my View is Empty File(cshtml). Even my Action is Empty logic just `return View();`

```
i found the problem is on FileExists  of RazorViewEngine.FileExists> 
BuildManagerViewEngine.FileExists>BuildManagerWrapper.FileExists>
BuildManager.GetObjectFactory>GetVirtualPathObjectFactory>
GetVirtualPathObjectFactory>GetVirtualPathObjectFactory>
GetVPathBuildResultWithAssert>GetVPathBuildResultWithNoAssert>GetVPathBuildResultInternal....
```
**im not sure why Empty View need so much time to compile.
so i guess,the bottleneck is not on the View Code Selfs,its just some logic code in mvc framework has some problem**

**is there any way to reduce the time ?**

Im using MVC4 and .net framework 4.0

Why Should Be I must Slove this Problems?
Because i have some web controls.
my page call the web controls,but controls first load is too slow!
some page i have more than 1 control.
then the speed is too many Slow.

**Comment by dougbu** [comment]
Hi. It looks like this is a question about how to use ASP.NET. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the 'asp.net' [tag](https://stackoverflow.com/questions/tagged/asp.net).

I believe the information in https://docs.microsoft.com/en-us/aspnet/web-forms/overview/older-versions-getting-started/deploying-web-site-projects/precompiling-your-website-cs remains relevant, especially the part about a Visual Studio publish options dialogue. (When enabled, publishing should pre-compile the .cshtml files.)

**Comment by sgf** [comment]
@dougbu i know,how to  pre-compile the Razor View Page.(but my means is when develop)
my question is.
**why it's compile a Empty View Page takes soo much time? 
u know the Empty View Page is no any Code.**

Do you really think there is no problem with such logic?

**Comment by dougbu** [comment]
@sgf is your complaint about a slowdown when building with pre-compiled views?

> Do you really think there is no problem with such logic?

It takes time to parse a view, write the C# out, and invoke the compiler whether or not the view contains C#. Moving this effort to build time is the recommendation.

**Comment by sgf** [comment]
That means nothing is actually done, but it's wasted 2-5 seconds on each page.
