### ISSUE TITLE
JsonMediaTypeFormatter doesn't work when Request is chunked

### ISSUE THREAD

**Issue by felipepessoto** [aspnet/AspNetWebStack#197]
When the request transfer-encoding is chunked, the request.ContentLength is 0 instead of null, then JsonMediaTypeFormatter return the default value (null for classes) in this line: https://github.com/aspnet/AspNetWebStack/blob/1a987f82d648a95aabed7d35e4c2bee17185c44d/src/System.Net.Http.Formatting/Formatting/BaseJsonMediaTypeFormatter.cs#L209

The workaround is: https://gist.github.com/jayoungers/0b39b66c49bf974ba73d83943c4b218b but it is just a workaround, and we don't know if it breaks other scenarios.

**Comment by dougbu** [comment]
I seem to remember an issue with chunking that may have been fixed recently. Which ASP.NET version are you using? And, which host e.g. IIS are you testing with?

**Comment by felipepessoto** [comment]
I tried with the latest version, 5.2.6

**Comment by dougbu** [comment]
Which host? A repro project, preferrably hosted in a GitHub repo, may help.

**Comment by felipepessoto** [comment]
@dougbu , the repro is here: https://github.com/felipepessoto/AspNetWebStack_197
It is just a clean project where I changed the ValuesController to receive a complex object.

The workaround is in Global.asax.

To reproduce you can use the ChunkedRequest.raz file with Fiddler, or create a request like this:

Headers:
```
User-Agent: Fiddler
Host: localhost:52841
Content-Type: application/json
Transfer-Encoding: chunked
```

Body:
```
D
{Name: "Joe"}
0


```

Be aware of the two line breaks in the end of body.

Thanks

**Comment by Tratcher** [comment]
No, there's no support for Transfer-Encoding: gzip. (it would be `Content-Encoding: gzip` anways).

Content-Length vs Chunked should be a non-issue for high level components like formatters. Only the server should need to worry about the distinction.

**Comment by dougbu** [comment]
> Only the server should need to worry about the distinction.

What about the case where the formatters are used in a client application?

Separately, I looked again and the `Content-Length` special case is specific to when ASP.NET hosts are creating responses. They should also special-case requests containing both headers.

**Comment by Tratcher** [comment]
On the client side as well, it's not the formatters job to validate content-length vs chunked. At most when they're generating a body they could avoid setting both.

**Comment by dougbu** [comment]
@Tratcher looks like something at a lower level than our web host _adds_ `Content-Length: 0` to the content headers whenever the request is chunked. Where is that likely happening? (I can't find any code in this repo that sets `Request.Content.Headers.ContentLength`.)

This happens whether or not the request has a non-empty body. Tested using Fiddler, with the following request bodies:
```
D
{Name: "Joe"}
0


```
and
```
0


```

**Comment by dougbu** [comment]
@felipepessoto the workaround described is incorrect because it _unconditionally_ resets a `0` `ContentLength` value to `null`. If done at all, this should only be done if the request is chunked.

**Comment by felipepessoto** [comment]
Yeah, I implemented using a different approach in project. This gist is what many people are using thought.

That's why we need a fix

**Comment by mkArtakMSFT** [comment]
Thanks for the investigation, @dougbu!
As this seems to be caused by an external (lower-level) aspect, please use this issue to track the workaround.

**Comment by Tratcher** [comment]
Let's look at the repro together next week. We should be able to narrow down the layering quickly.

**Comment by dougbu** [comment]
Removing `investigate` label. Root cause here is that `SeekableBufferedRequestStream.Length` value may be incorrect while its inner `Stream`'s `CanSeek == false`. Fixing that should fix the problem.

Alternate fix of changing the `HtmlContext` classes in web host to never guess `ContentLength` based on the body `Stream` could perhaps be more efficient. But, that would be a messier, larger change.

**Comment by dougbu** [comment]
523f3aa890

**Comment by dougbu** [comment]
Note we went with the "alternate fix" I [mentioned](https://github.com/aspnet/AspNetWebStack/issues/197#issuecomment-440477389) earlier, avoiding sync I/O

**Comment by felipepessoto** [comment]
The next release will include this fix? Do you already have an approximate release date?

Thanks

**Comment by dougbu** [comment]
The next release will include this fix. @danroth27 have we announced a specific date for 3.2.7?
