### ISSUE TITLE
Why is there no PatchAsJsonAsync(…) (et al.) method in HttpClientExtensions?

### ISSUE THREAD

**Issue by smarts** [aspnet/AspNetWebStack#202]

**Comment by dougbu** [comment]
@smarts ASP.NET supports many scenarios but does not include every imaginable feature. When more is needed, ASP.NET includes extensibility to enable them. For example, see http://benfoster.io/blog/adding-patch-support-to-httpclient

Separately, the [HttpClientExtensions](https://www.nuget.org/packages/HttpClientExtensions/) package is not part of this repository. Suggest filing your issue in https://github.com/alexanderpersson/HttpClientExtensions/issues

**Comment by smarts** [comment]
@dougbu unless these methods didn't make the cut for .net core/.net standard, then i'm not talking about another code base:
https://github.com/aspnet/AspNetWebStack/blob/master/src/System.Net.Http.Formatting/HttpClientExtensions.cs
That said, is this still the correct repository to be filing the issue?

**Comment by dougbu** [comment]
Ah, I thought you meant the package and not the class.

In any case, System.Net.Http.Formatting.dll has never included a `PatchAsJson(...)` feature though, as illustrated in http://benfoster.io/blog/adding-patch-support-to-httpclient, the extensibility points are sufficient to provide support. Please use that approach.

**Comment by smarts** [comment]
Thanks for the reply 🙂 
I understand that the assembly has never included these extension methods, and I'm also aware of the extension points available. My question was more about:
- understanding whether the exclusion (specifically of PATCH) was purposeful
- asking the question of whether the owners are open to adding support for PATCH (either by themselves or via a community contribution)

It does seem to be more of a first-class citizen (as opposed to, for example, TRACE, OPTIONS, & HEAD) since ASP.NET Core MVC has a [JsonPatch library](https://github.com/aspnet/JsonPatch).

I apologize that my initial post failed to ask my question clearly.

**Comment by dougbu** [comment]
Reopening temporarily.

I'll bring this up when we next triage issues in this repository (in a week or two). To be clear, I expect our guidance will be to move to ASP.NET Core or to use the extensibility points available here.

**Comment by dougbu** [comment]
We don't believe the utility here would be minimal because the patch JSON content could have many formats e.g. JSON Patch, JSON Merge, &hellip;

**Comment by smarts** [comment]
Thank you for taking the time to review.

**Comment by PeterLAxakon** [comment]
This is coming soon: https://learn.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-6.0
