### ISSUE TITLE
Whitespace (any uri escapable char) in virtual path root results in NoRouteFound in an WebApi/Owin setup

### ISSUE THREAD

**Issue by adzhiljano** [aspnet/AspNetWebStack#203]
Hello,

First of all, thank you very much for the Asp.Net and Katana!!!

I'm not entirely sure if this is an issue with WebApi or Katana or with the integration bits.

The environment is the following:

`Packages` (should be latest possible versions):

```
  <package id="Microsoft.AspNet.WebApi" version="5.2.6" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.6" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.6" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.Cors" version="5.2.6" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.Owin" version="5.2.6" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.6" targetFramework="net461" />
  <package id="Microsoft.Owin" version="4.0.0" targetFramework="net461" />
  <package id="Microsoft.Owin.Cors" version="4.0.0" targetFramework="net461" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="4.0.0" targetFramework="net461" />
  <package id="Microsoft.Owin.Security" version="3.1.0" targetFramework="net461" />
  <package id="Microsoft.Owin.Security.OAuth" version="3.1.0" targetFramework="net461" />
  <package id="Owin" version="1.0" targetFramework="net461" />
```
`Hosting`: IIS 10
`OS`: Win 10
`Site/App`: 'Virtual' application under the `Default Web Site (localhost:80)` with the name `test api`

But can be reproduced with the following minimal setup:
```
public void Configuration(IAppBuilder app)
{
	HttpConfiguration config = new HttpConfiguration();

	config.MapHttpAttributeRoutes();

	app.UseWebApi(config);
}
```

When I try to send a request to `http://localhost/test%20api/` I get a 404 and this is what I managed to trace:

1. The Uri related contents of the OwinRrequest (got it from a fake first middleware in the pipeline)
![1](https://user-images.githubusercontent.com/5879092/47230285-86070500-d3d2-11e8-996e-78291c01bb9b.JPG)
![2](https://user-images.githubusercontent.com/5879092/47230292-899a8c00-d3d2-11e8-8283-5d67e7c8f8fd.JPG)

2. The processing gets to a point where the the virtual path root is needed
https://github.com/aspnet/AspNetWebStack/blob/e0f1f1338e446f655f66b0d0859b64f0b964f3f5/src/System.Web.Http/HttpRouteCollection.cs#L82

and this is the current context:
![3](https://user-images.githubusercontent.com/5879092/47230721-ac797000-d3d3-11e8-81d9-d001ba2c3fb7.JPG)

3. Further a RoutingContext is needed
https://github.com/aspnet/AspNetWebStack/blob/e0f1f1338e446f655f66b0d0859b64f0b964f3f5/src/System.Web.Http/Routing/HttpRoute.cs#L154

and this is where the actual problem can be seen:
![4](https://user-images.githubusercontent.com/5879092/47230875-0f6b0700-d3d4-11e8-8d0e-d0ec8699c8bf.JPG)
It's trying to do 
`"/test api/".StartsWith("/test%20api", StringComparison.Ordinal)` which results in a `return RoutingContext.Invalid();` and then in a NoRouteFound.

I'll just share some additional info and my toughts:

An escapable character in the virtual path in a _pure_ (no Owin) WebApi setup is NOT a problem, it works as expected (I haven't debugged it though).

Please, keep in mind that I haven't gone that deep into the source codes so I might be missing something!

The way the virtual path root is retrieved maybe is the problem:
https://github.com/aspnet/AspNetWebStack/blob/e0f1f1338e446f655f66b0d0859b64f0b964f3f5/src/System.Web.Http.Owin/OwinHttpRequestContext.cs#L185

the `PathBase.ToString()` is actually `ToUriComponent()` which escapes the string.

https://github.com/aspnet/AspNetKatana/blob/e2b18ec84ceab7ffa29d80d89429c9988ab40144/src/Microsoft.Owin/PathString.cs#L60

and later on the `HttpRoute.CreateRoutingContext()` is doing (notice the `UriFormat.Unescaped`)
https://github.com/aspnet/AspNetWebStack/blob/e0f1f1338e446f655f66b0d0859b64f0b964f3f5/src/System.Web.Http/Routing/HttpRoute.cs#L157

and then those two are compared.

The only workaround that I found out was to use a custom `HttpRouteCollection` with an override of the
`public virtual IHttpRouteData GetRouteData(HttpRequestMessage request)` method so that I can unescape the virtual path root. Is there another way of doing this?

Thank you!

**Comment by dougbu** [comment]
@adzhiljano you've described a relatively low-level behaviour of the ASP.NET and Owin (Katana) code but not the user scenario in which an error occurs. That is, you've illustrated how `PathBase` and `Path` are retrieved and one place where the two are compared. But, what is the scenario, how does it fail e.g. are there unexpected 404s, and what changes when the app is self-hosted (not using Katana) or running in IIS or IIS Express?

That said, comparing escaped and unescaped values seems incorrect. Either Katana behaves differently from other ASP.NET hosts or another property should be used to ensure ASP.NET compares consistent (escaped or unescaped) values.

@Tratcher any other thoughts?

**Comment by adzhiljano** [comment]
Hey @dougbu,
The scenario is that whatever request is sent to `http://localhost/test%20api/**/*` (**arbitrary endpoint**) the result will be 404 - it's basically `app.Don'tUseWebApi(config);` middleware. Other middlewares work fine. There are only unexpected 404s for each and every endpoint one thought he registered. 

I'm not sure what you mean by 

> self-hosted (not using Katana)

I haven't tried it with `Microsoft.Owin.SelfHost`, but as I mentioned I tried it with 

> An escapable character in the virtual path in a pure (no Owin) WebApi setup is NOT a problem, it works as expected (I haven't debugged it though).

by which I meant running WebApi with no Owin (`GlobalConfiguration.Configure(WebApiConfig.Register);`) setup on IIS/IIS Express and it was working as expected - I was able to hit all endpoints.

And I'm pretty sure that the host is irrelevant in this case

You can reproduce the issue:
- create a new Web proj, 
- make a virtual directory with a whitespace in it's name 
- add an Owin Startup class with minimal setup:
```
public void Configuration(IAppBuilder app)
{
	HttpConfiguration config = new HttpConfiguration();

	config.MapHttpAttributeRoutes();

	app.UseWebApi(config);
}
```
- add Controllers
- try hitting any endpoint

**Comment by dougbu** [comment]
> I'm pretty sure that the host is irrelevant in this case

Why are you sure of that? The host provides the `PathBase` information. I'm trying to understand if hosts other than Katana are consistent.

**Comment by adzhiljano** [comment]
I got a bit confused there. When I was refering to the host, I meant an **Owin** host and this is why I said the host should be irrelevant. I tried different **ASP.NET** hosts and **Owin** hosts ([repo](https://github.com/adzhiljano/WebApiPathBaseTest)) and this is the summary for the url `http://localhost/test%20api/values`:

- **IIS/IIS Express** (Microsoft.AspNet.WebApi.WebHost) -> Working (200)
- **HttpSelfHostServer** (Microsoft.AspNet.WebApi.SelfHost) -> Working (200)
- **Owin** (Microsoft.AspNet.WebApi.Owin):
  - **IIS/IIS Express** (Microsoft.Owin.Host.SystemWeb) -> Not Working (404)
  - **HttpListener** (Microsoft.Owin.SelfHost) -> Not Working (404)
  - **HttpListener** (Microsoft.AspNet.WebApi.OwinSelfHost) -> Not Working (404)

**Comment by Tratcher** [comment]
Side note: don't mix Microsoft.Owin 3.1 and 4.0 components, upgrade everything.

I agree this looks like a format bug in the WebApi's Owin integration.

**Comment by dougbu** [comment]
37fce367eb
