### ISSUE TITLE
Run tests against latest versions of our dependencies

### ISSUE THREAD

**Issue by dougbu** [aspnet/AspNetWebStack#21]
All product code has outdated dependencies e.g. Newtonsoft.Json v6.0.4. Should test to see if tests run even when using the latest and greatest e.g. Newtonsoft.Json v9.0.1.

This issue is _not_ about the major breaking changes involved in updating our product dependencies. Likely choices are either to perform a one-time confirmation that our tests work fine or to (somehow) automate testing against both the minimum required versions and the latest.

**Comment by EdLichtman** [comment]
Hey dougbu,

It kind of seems like this task might need to be done pretty soon. I created a brand-new 4.6.1 application and now all of a sudden I can't use necessary nuget packages because the outdated reference to v6.0.4 is giving me dependency hell. I'm very much in favor of this task.
