### ISSUE TITLE
DropDownList - selecting item using SelectList not working correctly

### ISSUE THREAD

**Issue by ArmanHayots** [aspnet/AspNetWebStack#225]
Please check this one. DropDownListFor works good, while DropDownList not picking selected item and same behavior observed with multiselect version.

**Comment by dougbu** [comment]
Hi. It looks like this is a question about how to use ASP.NET. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the 'asp.net' [tag](https://stackoverflow.com/questions/tagged/asp.net).
