### ISSUE TITLE
ViewBag thread safety?

### ISSUE THREAD

**Issue by RichardD2** [aspnet/AspNetWebStack#226]
I have an application using MVC 5.2.6, which uses `async` actions. I need to load data for multiple drop-down lists from the database. I have been using a separate task for each list, combining them with `Task.WhenAll`, and awaiting the result.

For example:
```
private Task PopulateLookups(EventViewModel model, CancellationToken cancellationToken)
{
    async Task LoadDepartments()
    {
        var list = await Lookup.ListDepartments(cancellationToken).ConfigureAwait(false);
        ViewBag.Departments = list.Select(d => new SelectListItem
        {
            Value = d.Number.ToString(),
            Text = d.Name,
            Selected = d.Number == model.DepartmentNumber,
        });
    }

    async Task LoadPropositions()
    {
        var list = await Lookup.ListPropositions(cancellationToken).ConfigureAwait(false);
        ViewBag.Propositions = list.Select(e => new SelectListItem
        {
            Value = e.Number.ToString(),
            Text = e.Name,
            Selected = e.Number == model.PropositionNumber,
        });
    }

    return Task.WhenAll(
        LoadDepartments(),
        LoadPropositions());
}

[HttpGet]
public async Task<ActionResult> Edit(int id, CancellationToken cancellationToken)
{
    var data = await DataSource.LoadEvent(id, cancellationToken).ConfigureAwait(false);
    if (data is null) return RedirectToAction(nameof(Index));
    
    var model = new EventViewModel(data);
    await PopulateLookups(model, cancellationToken).ConfigureAwait(false);
    return View(model);
}
```

99.9% of the time, this works perfectly. However, I have recently seen a few exceptions which suggest that this is not entirely safe:

> System.IndexOutOfRangeException
> Index was outside the bounds of the array.
> at System.Collections.Generic.Dictionary\`2.Insert(TKey key, TValue value, Boolean add)
> at System.Web.Mvc.DynamicViewDataDictionary.TrySetMember(SetMemberBinder binder, Object value)
> at CallSite.Target(Closure , CallSite , Object , IEnumerable\`1 )
> at MyNamespace.EventsController.<>c__DisplayClass8_0.<<PopulateLookups>g__LoadDepartments|0>d.MoveNext() 

From what I can see, `ViewBag` is a `DynamicViewDataDictionary`, which wraps a `ViewDataDictionary`, which in turn wraps a `Dictionary<string, object>`. The generic dictionary class is not thread-safe, and there is no attempt to prevent multiple threads from writing to this dictionary simultaneously.

Is this something that's been overlooked, or is it just not supported?

If it's not supported, then I think there needs to be a warning in the documentation.

**Comment by dougbu** [comment]
> Is this something that's been overlooked, or is it just not supported?

It's just not supported.

I recommend making a slight change to collect everything asynchronously then set the `ViewBag` properties synchronously. Of course `Lookup.ListDepartments(...)` also needs to return a `Task` suitable for use with `ConfigureAwait(false)`.

For example, there's a lot of synchronous code that can be removed from the inner `Task`s:
``` c#
private async Task PopulateLookups(EventViewModel model, CancellationToken cancellationToken)
{
    // May be faster to execute `var departments = await ...` then `var propositions = await ...`.
    IEnumerable<?> departments;
    IEnumerable<?> propositions;

    async Task LoadDepartments()
    {
        departments = await Lookup.ListDepartments(cancellationToken).ConfigureAwait(false);
    }
    async Task LoadPropositions()
    {
        propositions= await Lookup.ListPropositions(cancellationToken).ConfigureAwait(false);
    }

    await Task.WhenAll(LoadDepartments(), LoadPropositions());

    ViewBag.Departments = list.Select(d => new SelectListItem
    {
        Value = d.Number.ToString(),
        Text = d.Name,
        Selected = d.Number == model.DepartmentNumber,
    });
    ViewBag.Propositions = list.Select(e => new SelectListItem
    {
        Value = e.Number.ToString(),
        Text = e.Name,
        Selected = e.Number == model.PropositionNumber,
    });
}
```

**Comment by RichardD2** [comment]
Thanks for confirming that. I'll probably just add the lists as properties on my view model instead.
