### ISSUE TITLE
Update readme.md to explain which versions correspond to which tags

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetWebStack#23]
See original discussion here: https://aspnetwebstack.codeplex.com/discussions/657260

> Unfortunately there's probably not good docs on it right now (that I'm aware of). The problem is that the repo contains several different projects: MVC, Web API, Razor, and Web Pages. Each one has its own version (they came out at different times). So because of that, there isn't one simple version tag that we can use. 
> 
> We're looking to clean some stuff up in this repo, so I'll make a note to add some doc/wiki entry that explains the tags/branches in the repo.

**Comment by Eilon** [comment]
Thinking something like a little table:

```
<link to a version tag> | <MVC version> | <Web API version> | <Web Pages version>
...
repeat for each of the latest x.y tags
```

**Comment by dougbu** [comment]
7dad2002a8
