### ISSUE TITLE
Issue with using ModelState

### ISSUE THREAD

**Issue by DimQ1** [aspnet/AspNetWebStack#230]
``` c#
object defaultValue = (allowMultiple) ? GetModelStateValue(Name, typeof(string[])) : GetModelStateValue(Name, typeof(string));
```
This code wrong.
If you get model in controller and validate it you have cached input data and this code use wrong data.

**Comment by dougbu** [comment]
Thank you for contacting us.

To evaluate this feature request, we'd like to understand more about your scenario. Could you please elaborate on the scenario and the problem you're trying to solve?

For example, where are you seeing the code you quoted?

**Comment by dougbu** [comment]
@DimQ1 thank-you for your feedback. We're closing this issue as no updates have been provided in a timely manner and we do not have enough information to reproduce the issue. If you have more details and are still encountering this issue, please add a new reply and re-open the issue.
