### ISSUE TITLE
MVC 5: Antiforgery token cookie not present on mobile after reopening android chrome after long time 

### ISSUE THREAD

**Issue by omuleanu** [aspnet/AspNetWebStack#234]
I have the `@Html.AntiforgeryToken()` in `_Layout.cshtml`
I'm adding the antiforgery token to post ajax requests,

on Chrome Android (mobile phone) if I open the website it works ok, after close chrome and open it after 1 day  the page will load but all the requests with antiforgery with token will fail saying that there is no `_RequestVerficationToken` cookie
and after refresh it works.

I also used to have a problem when after reopening android chrome after 30 min was getting a something like `antiforgery webfarm` error message but that I solved by adding a `machineKey` to the `web.config`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
