### ISSUE TITLE
Not a Issue. Is a Question: What is the ASP.NET MVC (Full Framework) Roadmap? 

### ISSUE THREAD

**Issue by oerodriguezn** [aspnet/AspNetWebStack#236]
What is the ASP.NET MVC (Full Framework) Roadmap? I cant find it anywhere

**Comment by danroth27** [comment]
We don't have any major releases planned for ASP.NET MVC at this time. Most of our efforts right now are focused on ASP.NET Core. We will address critical issues in ASP.NET MVC and ship updates as they come up in a reactive fashion. If there are any particular issues that you are waiting for a resolution on please let us know.
