### ISSUE TITLE
Disable warning 1591

### ISSUE THREAD

**Issue by grosch** [aspnet/AspNetWebStack#238]
None of your public methods are documents with XML doc comments, resulting in tons of warnings from the compiler.  Would you please include a '#pragma warning disable 1591' at the top of each generated source file?

**Comment by Eilon** [comment]
You're saying then when you enable 1591 in your ASP.NET MVC project, you get a lot of spurious warnings from generated code?

**Comment by grosch** [comment]
No, I'm saying that by default the generated code has a ton of warnings when XML documentation generation is enabled.  I'd like you to add that pragma at the top of each file so that we do *not* get the warnings about public methods that don't have appropriate XML doc comments on them.

**Comment by grosch** [comment]
Any possibility of this happening?

**Comment by Eilon** [comment]
Hi @grosch , I just created a new ASP.NET MVC 5 project in VS2019 and I don't see any warnings. Can you please provide more info on how to reproduce the issue you're seeing?

**Comment by grosch** [comment]
I don't know exactly how I enabled it.  I thought just checking the "XML documentation file" in the build tab of the project properties was enough to turn it on.

Regardless, the issue is just that I DO have them enable, and I DO want them enabled, but I don't want to see all the warnings for the code you generate from the NuGet package.  By putting the pragma into your source it doesn't change how any of the code works, but ensures I won't get any missing doc comment warnings for those files.

**Comment by grosch** [comment]
Ugh, I'm starting to see the issue.  This is for the Microsoft.AspNet.WebApi.HelpPage package, and their page links to yours, which seems to probably not be correct.  Are you the one generating the Areas/HelpPage stuff?

**Comment by Eilon** [comment]
Ah, the Web API help page. The source for that is indeed part of this repo: https://github.com/aspnet/AspNetWebStack/tree/master/src/WebApiHelpPage

It's certainly tricky when it comes to making a "source package" (that is, a package that adds source code to the target project) on how to handle various project settings in the target project. There are many kinds of warnings or even errors that can show up: style guidelines, the XML doc comment warning you encountered, or other design-time or build-time checks. Sometimes part of the solution is to indicate that the files are "generated" files, but that isn't true if the files are meant to be edited in the target project (which I believe is the case here). One workaround is to go ahead and edit the files in your project to adapt them to any project/compiler settings that you have adjusted.

Having said that, it might make sense in this project to either:
1. Add the `#pragma` as you suggest
2. Add doc comments to the public methods in this project to avoid the warning

But, I don't work on this project, so I don't have very much say on it. Feel free to re-open the bug for further consideration.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're not making any improvements in this area any more as this project is in maintenance mode. Only critical blocking issue with wide impact and security issues are considered.
