### ISSUE TITLE
Adding a new RemoteAttribute seems to cause other EF6 attributes to be ignored

### ISSUE THREAD

**Issue by Tiberriver256** [aspnet/AspNetWebStack#253]
This will have an index created:
```csharp
public class MyClass {
   [Index(IsUnique = true)]
   public string MyProperty {get; set;}
}
```

No index will be created:
```csharp
public class MyClass {
   [Index(IsUnique = true)]
   [Remote("MyValidationMethod", "MyController", ErrorMessage = "MyErrorMessage")]
   public string MyProperty {get; set;}
}
```
Using v5.2.7 of Microsoft.AspNet.Mvc and EF v6.2.0

**Comment by Tiberriver256** [comment]
My workaround for now was to use the DbModelBuilder and the fluent api to put in the typical annotations.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Glad that you have a workaround available.

We're not making any improvements in this area any more as this project is in maintenance mode. Only critical blocking issue with wide impact and security issues are considered.
