### ISSUE TITLE
Error building the source for tag v3.2.6

### ISSUE THREAD

**Issue by Sathyaish** [aspnet/AspNetWebStack#261]
I have Visual Studio 2019 on Windows 10.

I want to set up the source code for version 5.2.6 of ASP.NET MVC on my local dev machine, so I checked out the tag `v3.2.6` in git in my local repo and ran the **build.cmd** file in the repo root.

It failed with the following error message.

````
> build
Could not find MSBuild.exe. Please install the VS2017 BuildTools component 
or a workload that includes it.

*** BUILD FAILED ***

````
I read each line of the **build.cmd** file and came to the conclusion that the check that checks for the existence of **MSBuild.exe** on line 32 failed.

````
if exist "%InstallDir%\MSBuild\15.0\Bin\MSBuild.exe"
````

I have always had MSBuild [(in fact, several versions of it](https://stackoverflow.com/q/53262222/303685)) installed on my machine. So, upon a further probe, I realized that the variable `%InstallDir%` was still set to a null string even after executing the for-loop in line  29 of the script in the file build.cmd.

````
set InstallDir=
for /f "usebackq tokens=*" %%i in (`%vswhere% -latest -
prerelease -products * -requires Microsoft.Component.MSBuild 
-property installationPath`) do (
  set InstallDir=%%i
)
````
I couldn't go further than that in tracing the problem because to make sense of that for-loop, I'd have to re-learn batch programming, which I think would be a huge waste of my time, especially if someone who already had set the source up on their machine could just tell me in 5 minutes what to do.

So, I wrote to the person who tagged the commit. They replied that I needed Visual Studio 2017 installed for that tag to build.

[So, I downloaded and installed Visual Studio 2017 Community 15.9](https://stackoverflow.com/q/58091113/303685) side-by-side with my previous installation of Visual Studio 2019 Community.

However, the build still failed with the same message.

I looked around the VS2017 installer for anything called **BuildTools** component [but couldn't find one](https://stackoverflow.com/q/58099246/303685), so someone on StackOverflow [advised that it was a separate install](https://stackoverflow.com/a/58103324/303685). I installed that one, too.

But the message still persists.

It turns out that I've already spent more than 2 days at this.

Can someone please tell me how to build the source and set it up on my machine? Is there a read me file that walks you through these steps?

**Comment by dougbu** [comment]
@Sathyaish the loop you highlighted goes through the VS installations on your machine to find the latest instance of VS. The line you highlighted from after that loop looks for `msbuild.exe` in a location specific to a VS 2017 installation.

We can't update the tag because that's what we built for the 3.2.6 release. However, you can either build the v3.2.7 tag or master to avoid these issues.

The alternative is to make a local change in build.cmd while sticking with the 3.2.6 tag. In particular, add `-version ^[15^,16^)` to the `%vswhere%` command line e.g. 
``` powershell
for /f "usebackq tokens=*" %%i in (`%vswhere% -version ^[15^,16^) -latest -prerelease -products * -requires Microsoft.Component.MSBuild -property installationPath`) do (
```

**Comment by dougbu** [comment]
@Sathyaish thank-you for your feedback. We're closing this issue as the questions asked here have been answered. Please reopen if something is not clear.

**Comment by Sathyaish** [comment]
@dougbu Thank you. The build passes now. That was all the help I needed. Thanks much. :-)
