### ISSUE TITLE
HttpResponseMessage Serialisation still breaks in .NET Core 3.0

### ISSUE THREAD

**Issue by aliostad** [aspnet/AspNetWebStack#263]
This is related to https://github.com/dotnet/corefx/issues/31918 and the same repro described there breaks with .NET 3.0 but the reason appears to be different and due to not using `TryAddWithoutValidation` according to [this](https://github.com/dotnet/corefx/issues/31918#issuecomment-543414911).

Basic issue is that headers such as `Expires: -1` are not supported while they are still prevalent.

**Comment by aliostad** [comment]
![tenor](https://user-images.githubusercontent.com/487334/67485045-37cdb700-f661-11e9-945d-7ec79a0c0bcf.gif)

**Comment by jkonecki** [comment]
This issue has been present since .NET Core 2.1!

@aliostad keeps opening new bugs after we are told the issue has been fixed. Could someone PLEASE take a look at it and sort it out once and for all?!

**Comment by dougbu** [comment]
c55dd95aebb2
