### ISSUE TITLE
Attaching a zip to an HTTPResponseMessage over Owin does not work

### ISSUE THREAD

**Issue by isaachazan** [aspnet/AspNetWebStack#264]
When trying the following code over Owin:

`        public HttpResponseMessage DownloadDebug()
        {
            Console.WriteLine("Download debug");

            string filepath = @"c:\temp\MyLogs_2018-07-12T10-56-16.zip";
            var dataBytes = File.ReadAllBytes(filepath);
            var dataStream = new MemoryStream(dataBytes);

            HttpResponseMessage httpResponseMessage = Request.CreateResponse(HttpStatusCode.OK);
            //httpResponseMessage.Content = new StreamContent(new FileStream(filepath, FileMode.Open, FileAccess.Read));
            httpResponseMessage.Content = new StreamContent(dataStream);
            httpResponseMessage.Content.Headers.ContentDisposition = new System.Net.Http.Headers.ContentDispositionHeaderValue("attachment");
            httpResponseMessage.Content.Headers.ContentDisposition.FileName = "MyLogs_2018-07-12T10-56-16.zip";
            httpResponseMessage.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/zip");

            return httpResponseMessage;
        }
`

This does return the file but for some reason it's twice the size of the file and the Zip is invalid in the sense no zip software can open it saying: "Unable to seek to central directory"

I tried a few other options like using a filestream instead or using other media types like octet-stream or x-compressed but none of them worked

Thank you for any help

**Comment by Tratcher** [comment]
The code seems fine.

What client are you using to download the file? And which are you using to open it? Can that client open the original file on the server?
