### ISSUE TITLE
SameSite cookie: browser sniffing for non-Owin project 

### ISSUE THREAD

**Issue by thuannguy** [aspnet/AspNetWebStack#267]
I have a bunch of web applications that use WIF/System.IdentityModel. I want to do browser sniffing to support old browsers as described at https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/.

The cookies that I need to set to None/Empty depending on what browser is used are:

- SessionId cookie.
- Forms Authentication cookie.
- FedAuth cookie.

Problem is that my applications aren't using Owin. Where is the best place for me to apply code that does browser sniffing when:

1. An application is using MVC.
2. An application is using Web forms.

Best Regards,
Thuan.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net** tag.

**Comment by thuannguy** [comment]
Hi,
Because I was asking about using WIF/System.IdentityModel, Owin, and Webforms, my question doesn't appear to be about Asp.Net Core. I'm fine with diverting to StackOverflow, but it seems to me that my question was closed without even being read carefully.
The reason that I had to ask here is because of lack of documentation for Asp.Net MVC/Webforms. For the record, I asked on StackOverflow as well without any luck.

**Comment by mkArtakMSFT** [comment]
@thuannguy, we are a relatively small team and it's unfortunate that we can't afford investigating everything. Given the limited resources we carefully choose the investments we make and focus only common pain points to help the general community as much as possible. In this particular case, we did read the question, but the triage team didn't have the deep knowledge to guide you. Given that this question has been impacting only you it didn't meet the bar for us to dedicate team resources on looking into this. In these situations, we always refer our customers to StackOverflow.

**Comment by thuannguy** [comment]
@mkArtakMSFT totally understood. Thank you for your time :) As a side note, I really appreciated help that I got from the Asp.Net folks, especially on Twitter.
