### ISSUE TITLE
RemoteAttribute Bind Prefix Unobtrusive Validation 

### ISSUE THREAD

**Issue by shapemetrics** [aspnet/AspNetWebStack#268]
Scenario:
Model:

public class MyModel{
[Remote("action","controller")]
public string validateThis{get;set;}
}

When utilizing an attribute on a modal dialog for a group of elements (different models), using the Name/id htmlattributes on the above model. The validation is triggered with a red highlighted field when invalid, but the message does not show. I found the issue is related to the htmlattributes (Name/id), as I put a manual validation message helper for the static name produced, which produces the validation. However, it does not trigger a validation summary when using the onblur normally, while it does when you attempt to submit the form.

**Comment by mkArtakMSFT** [comment]
Thank you for contacting us. We are currently only fixing critical functional issues in the code base, and have decided to not make this change.
