### ISSUE TITLE
FormUrlEncodedMediaTypeFormatter.ReadFromStreamAsync is synchronous

### ISSUE THREAD

**Issue by freerangegreg** [aspnet/AspNetWebStack#270]
I've recently switched over to Azure Functions v3 (core 3.1) and got hit by the new requirement that everything is synchronous: https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnetcore#http-synchronous-io-disabled-in-all-servers

This causes issues with using `HttpContentFormDataExtensions.ReadAsFormDataAsync` to parse form data. This eventually calls `FormUrlEncodedMediaTypeFormatter.ReadFromStreamAsync`, which is a thin wrapper over a synchronous implementation. The fix would be to write a proper async version.

**Comment by mkArtakMSFT** [comment]
Thank you for contacting us. We are currently only fixing critical functional issues in the code base, and have decided to not make this change.
