### ISSUE TITLE
Handle multiple member names in ValidationResult when using custom ValidationAttribute

### ISSUE THREAD

**Issue by nszabi** [aspnet/AspNetWebStack#272]
The ModelState doesn't get populated with multiple keys when a custom ValidationAttribute returns a invalid ValidationResult that has multiple MemberNames. If I investigated correctly, this issue was already fixed in ASP.NET Core 2.0.0, the link to that ticket is [here](https://github.com/aspnet/Mvc/issues/3595).

Issue is happening on ASP.NET MVC (non-Core) version 5.2.7

**Comment by mkArtakMSFT** [comment]
Thank you for contacting us. We are currently only fixing critical functional issues in the code base, and have decided to not make this change.
