### ISSUE TITLE
Web API does not publish in 4.7.2

### ISSUE THREAD

**Issue by CGollhardt** [aspnet/AspNetWebStack#275]
When trying to publish a WebAPI with precompiled views (**EnableUpdateable = False**), this always fails:

Relevant Output:

    2>aspnet_merge(0,0): Error occurred: An error occurred when merging assemblies: Unresolved assembly reference not allowed: System.Net.Http.

Publish Profile:

    <Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
      <PropertyGroup>
        <WebPublishMethod>FileSystem</WebPublishMethod>
        <PublishProvider>FileSystem</PublishProvider>
        <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
        <LastUsedPlatform>Any CPU</LastUsedPlatform>
        <SiteUrlToLaunchAfterPublish />
        <LaunchSiteAfterPublish>True</LaunchSiteAfterPublish>
        <ExcludeApp_Data>True</ExcludeApp_Data>
        <publishUrl>bin\Release\Publish</publishUrl>
        <DeleteExistingFiles>True</DeleteExistingFiles>
        <PrecompileBeforePublish>True</PrecompileBeforePublish>
        <EnableUpdateable>False</EnableUpdateable>
        <DebugSymbols>False</DebugSymbols>
        <WDPMergeOption>MergeAllOutputsToASingleAssembly</WDPMergeOption>
        <UseMerge>True</UseMerge>
        <SingleAssemblyName>Views</SingleAssemblyName>
      </PropertyGroup>
    </Project>

Studio Version: Version 16.5.3
Framework: 4.7.2

This can be reproduced by creating a new Web API project via the default Template, and above publish configuration.

Any pointers?

Full Output:

    1>------ Build started: Project: WebApplication2, Configuration: Release Any CPU ------
    1>  WebApplication2 -> D:\Conwell\OnlineSystem\Dev\WebApplication2\bin\WebApplication2.dll
    2>------ Publish started: Project: WebApplication2, Configuration: Release Any CPU ------
    2>Connecting to D:\Conwell\OnlineSystem\Dev\WebApplication2\bin\Release\Publish...
    2>Transformed Web.config using D:\Conwell\OnlineSystem\Dev\WebApplication2\Web.Release.config into obj\Release\TransformWebConfig\transformed\Web.config.
    2>Copying all files to temporary location below for package/publish:
    2>obj\Release\AspnetCompileMerge\Source.
    2>C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\aspnet_compiler.exe -v / -p D:\Conwell\OnlineSystem\Dev\WebApplication2\obj\Release\AspnetCompileMerge\Source D:\Conwell\OnlineSystem\Dev\WebApplication2\obj\Release\AspnetCompileMerge\TempBuildDir 
    2>Running aspnet_merge.exe.
    2>C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\aspnet_merge.exe D:\Conwell\OnlineSystem\Dev\WebApplication2\obj\Release\AspnetCompileMerge\TempBuildDir -o Views -copyattrs obj\Release\AssemblyInfo\AssemblyInfo.dll -a  
    2>aspnet_merge(0,0): Error occurred: An error occurred when merging assemblies: Unresolved assembly reference not allowed: System.Net.Http.
    2>
    ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
    ========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

I already tried several things, such as assembly rebinding, reference the nuget package of `System.Net.Http` (private), switching to Package References, Reinstall Packages, referencing NetStandard,

Also tried to reference the following Packages:

- NETStandard.Library
- Microsoft.NETCore.Platforms
- Microsoft.AspNet.Merge

Also tried to modify the web.config to:

    <compilation debug="true" targetFramework="4.7.2">
	    <assemblies>
		    <add assembly="netstandard, Version=2.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"/>
	    </assemblies>
    </compilation>
    <httpRuntime targetFramework="4.7.2"/>

And

    <system.codedom>
      <compilers>
        <compiler language="c#;cs;csharp" extension=".cs" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=2.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:6 /nowarn:1659;1699;1701"/>
        <compiler language="vb;vbs;visualbasic;vbscript" extension=".vb" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=2.0.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:14 /nowarn:41008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+"/>
      </compilers>
    </system.codedom>

Above Problem is simplified, to be reproduceable, but in reality I have a big WebAPI which needs to support 4.7.2 in order to support net standard 2.0

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We haven't heard a lot of community feedback about this particular problem.   Given that we also try to limit our changes to only most critical fixes we have decided to close this issue.

**Comment by farlop** [comment]
Hi @CGollhardt 
I'm currently running into the same problema in a legacy project. Did you manage to solve this issue?
Thanks!

**Comment by CGollhardt** [comment]
@farlop Sorry, bad news are, I didn't

The workaround we used, was not precompiling the views. It doesn't hurt that much, cause the API itself it Compiled in production, just the help pages are jit compiled.

If somebody comes up with a solution, It would still be nice about being notified :)

**Comment by farlop** [comment]
Thank you so much for answering. That's what I've ended up with.
