### ISSUE TITLE
Shouldn't the StreamReader be disposed here?

### ISSUE THREAD

**Issue by Bouke** [aspnet/AspNetWebStack#276]
https://github.com/aspnet/AspNetWebStack/blob/ebef5b7d821b64ed5c48765d0caf6ce8a9bcfaf5/src/System.Web.Mvc/JsonValueProviderFactory.cs#L51

The StreamReader isn't disposed, which I suppose should happen here?

**Comment by Bouke** [comment]
By default StreamReader will close the stream it's reading from. This would close the request's input stream, which is not desired. Looking at [StreamReader.Dispose](https://referencesource.microsoft.com/#mscorlib/system/io/streamreader.cs,011147a163b10458,references) it looks like closing the stream is the only thing it does. So it probably doesn't really matter that much, other than not disposing an IDisposable looking like a code smell.

**Comment by dougbu** [comment]
At worst the `StreamReader` object will live a little longer. Not worth using the (ugly) constructor that tells the `StreamReader` it doesn't own the underlying `Stream`.
