### ISSUE TITLE
AntiForgeryToken mismatch with multiple tabs (race condition?)

### ISSUE THREAD

**Issue by CollenIrwinDSS** [aspnet/AspNetWebStack#278]
### Title
AntiForgeryToken mismatch exception is thrown when multiple tabs of the same view are opened in quick succession, upon submitting the form in said view.

### Functional impact
`System.Web.Mvc.HttpAntiForgeryException` is thrown on some of the pages upon posting to an action that validates the page's anti-forgery token.

### Minimal repro steps
See minimal repro repository [here](https://github.com/CollenIrwinDSS/AntiForgeryRepro).
Demonstration using above repository:
![demonstration](https://user-images.githubusercontent.com/53623839/79247853-0502bf80-7e49-11ea-9f35-ed9eda0f87c0.gif)

### Expected result
The pages submit normally with no `System.Web.Mvc.HttpAntiForgeryException`.

### Actual result
`System.Web.Mvc.HttpAntiForgeryException` is thrown when submitting some of the pages.

### Further details
I have tested this in Chrome 81 and Firefox 75.
This seems to be a similar problem to the one documented [here](https://github.com/dotnet/aspnetcore/issues/2882) in the aspnetcore repo, but it doesn't appear that anyone was able to reproduce it.

**Comment by CollenIrwinDSS** [comment]
For clarity: the reason I think this could be a race condition is that if the pages are not opened in quick succession (ie you wait for each page to finish loading before the next is opened), the problem does not arise.

**Comment by mkArtakMSFT** [comment]
Thank you for contacting us. We are currently only fixing critical functional issues in the code base, and have decided to not make this change.
