### ISSUE TITLE
CORS methods = "get,post" won't work when posting but "post" or "post,get" work

### ISSUE THREAD

**Issue by MihaMarkic** [aspnet/AspNetWebStack#288]
I have a situation when CORS methods filtering "get,post" won't work when posting but "post" or "post,get" work.
The method in question is [HttpPost] only.
Works:
```csharp
[EnableCors(origins: "*", headers: "*", methods: "*")]
[EnableCors(origins: "*", headers: "*", methods: "post")]
[EnableCors(origins: "*", headers: "*", methods: "post,get")]
```
Does not
```csharp
[EnableCors(origins: "*", headers: "*", methods: "get,post")]
```
Am I missing something obvious?

**Comment by dougbu** [comment]
@pranavkm any ideas❔

@MihaMarkic my main thought is that "GET,POST" might work better depending on the comparisons MVC does under the covers.

**Comment by pranavkm** [comment]
Not sure. I don't see anything particularly suspicious in the code:

* https://github.com/aspnet/AspNetWebStack/blob/master/src/System.Web.Http.Cors/EnableCorsAttribute.cs#L87-L97
* https://github.com/aspnet/AspNetWebStack/blob/master/src/System.Web.Cors/CorsEngine.cs#L84-L113
* https://github.com/aspnet/AspNetWebStack/blob/8044f4ea5cb14b43ef4f8f6f065a98cc38c7d3b8/src/System.Web.Http.Cors/CorsMessageHandler.cs#L174-L184

Do you happen to see a 400 error response from the server? That would at least indicate that the cors policy was processed. Regardless, if one of the options works (using `methods: "post,get"`), I would continue using it.

**Comment by MihaMarkic** [comment]
@pranavkm @dougbu I can't reproduct it anymore. Perhaps it was my error or a very specific combination of something.
