### ISSUE TITLE
Empty JSON array binds to a null in MVC controllers

### ISSUE THREAD

**Issue by TKharaishvili** [aspnet/AspNetWebStack#292]
Given a model and a controller
```C#
public class SimpleModel
{
    public List<int> Integers { get; set; }
}

public class SimpleController : Controller
{
   [HttpPost]
   public ActionResult Create(SimpleModel model)
   {
      return Content(model.Integers == null ? "sad" : "happy");
   }
}
```
when I post the payload
```
{
   "integers": []
}
```
with the appropriate `content-type` header `model.Integers` property gets bound to `null` instead of an empty list. The same is not true for api controllers though, the binder works as expected there.

This looks like a bug to me, however I can see how some legacy code might actually depend on this making fixing it a breaking change.
I still would like to see it fixed though, maybe behind a feature flag or some kind of a setting.
I know there's next to no new development in this repo any more but I'm open to fixing this myself with some small guidance from somebody knowledgeable with the codebase.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We won't be able to change this as it'll break existing customers who rely on this behavior.
