### ISSUE TITLE
NuGet Gallery License Information

### ISSUE THREAD

**Issue by aluitink** [aspnet/AspNetWebStack#303]
Hello, 
I noticed the license in the source is Apache 2.0, but the licenses information associated with most of the NuGet packages point to:

[.NET Library](https://www.microsoft.com/web/webpi/eula/net_library_eula_ENU.htm)

Can the License info on the NuGet packages be updated to reflect the license associated with the source?

**Comment by dougbu** [comment]
@Pilchie please do the needful, as @mkArtakMSFT said you're doing similar work in other repos

**Comment by dougbu** [comment]
@aluitink, we discussed this issue internally and agree the licenses in the code and package metadata are inconsistent. That inconsistency will remain when we ship 5.2.8 and going forward. To do otherwise would cause unnecessary churn in packages we rarely ship.

Many thanks for the issue❗ It resulted in an interesting conversation.

**Comment by mardet** [comment]
@dougbu, sorry to comment on a closed issue. I understand from the message above that the plan is not to fix the inconsistency in licenses (which is up to you to decide). However, this leaves me with the doubt of which license applies in which case.
Could you just clarify which license applies when using the [Nuget](https://www.nuget.org/packages/Microsoft.AspNet.Mvc/5.2.9/)? and which license apply when compiling the source code of this repository?
Is [this](https://www.nuget.org/packages/Microsoft.AspNet.Mvc/5.2.9/License) a custom license from Microsoft? would the category of this be some type of Open Source license or Commercial one?
I am just trying to categorize the licenses we use in our software (we are using the Nuget) and I am a bit stuck with this one
