### ISSUE TITLE
Uploading many files by chunk using ajax async causing HTTP request hang on the server when using SSL with HTTP2 protocol

### ISSUE THREAD

**Issue by filmar25** [aspnet/AspNetWebStack#306]
Hi,

I was working on a problem for more than a week now. After a lot of tests, and thanks to DevExpress than give me a good direction about our problem, we found that our behavior is caused by the HTTP2 protocol. We don't know yet why it is causing that.

In our solution, we allow to upload more than one file at once. We are using Promise to upload files separately and each file is send by chunks. If we send 10 files, 10 async ajax call are send to our application. But in HTTPS, the call still "Pending" and on the server we see that HTTP Request are well received, but not executed. But the problem is not happening if we upload only few files, like 4,5 or 6. Over that number, all http request hang.

But if we use HTTP protocol, we don't have this hang on the server. We also deactivated HTTP2 by create in the registry the required keys to do that. After deactivate HTTP2, we can use HTTPS protocol to upload files by chunks without any problem.

Just mention that we have created another ASP.NET MVC 5 test project and it is working perfectly with HTTP2. So it is likely we have a reference in our project that is causing the problem, but it is very hard to find.

Can anyone can give us tips to resolve this problem ?

Any help will be very appreciated.

Thank you !

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This doesn't seem to be framework related especially given that you've been able to get this work successfully with a new app.
Raising this question in [StackOverflow](https://stackoverflow.com) may be the best next step. Given that there is no pending action from us here we're closing this issue.

**Comment by CZEMacLeod** [comment]
@filmar25 This sounds like a similar problem to one I saw over on the Katana repo - https://github.com/aspnet/AspNetKatana/issues/430 - maybe it is related and has a possibly similar solution.
If not - it might give inspiration or at least something to rule out.
HTH
