### ISSUE TITLE
Disable tooling build for WSR.Main

### ISSUE THREAD

**Issue by joeloff** [aspnet/AspNetWebStack#31]
Tooling is building in separate branches since 5.2.3 shipped in 2013.

We should just make WSR.Main build runtime DLLs/packages and update the CI accordingly.

We have plans to eventually move all the tooling code into WTE

**Comment by dougbu** [comment]
@joeloff I'm working to address this and may have lost some of the context. When you said "No, those are all used." [above](https://github.com/aspnet/AspNetWebStack/issues/31#issuecomment-266131190) did you mean the runtime builds on our CI should create those packages?

**Comment by dougbu** [comment]
Completed with TFS check-ins and DI configuration changes.
