### ISSUE TITLE
Not Compatible with Sync HttpClient Send

### ISSUE THREAD

**Issue by microalps** [aspnet/AspNetWebStack#363]
### Functional impact
Unable to utilize new Send method implemented in NET5 - https://github.com/dotnet/runtime/pull/34948

### Expected result
Return a response, same as awaiting the async version. ObjectContent does not implement SerializeToStream (even though the formatters seem to).

### Actual result
 NotSupportedException: The synchronous method is not supported by 'System.Net.Http.ObjectContent`1[T]'. If you're using a custom 'HttpContent' and wish to use synchronous HTTP methods, you must override its 'SerializeToStream' virtual method.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The changes in .NET (Core) are not applicable to AspNetWebStack, as it's not a .NET Core technology. AspNetWebStack runs on .NET Framework. It's not currently in active development and only critical bugs or security issues are being addressed.
