### ISSUE TITLE
NuGet package license missing French clauses for Quebec

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [aspnet/AspNetWebStack#376]
### Title
The EULA falsely claims that some clauses are "provided below in French."

### Functional impact
No

### Minimal repro steps
1. Open <https://www.nuget.org/packages/Microsoft.AspNet.WebApi/5.2.9/License> in a Web browser.
2. See that the license agreement ends with:
   > Please note: As this software is distributed in Quebec, Canada, some of the clauses in this agreement are provided below in French.

### Expected result
Either the clauses are actually provided in French like the note claims, or the note is removed.

### Actual result
The note references French translations that are not published with the EULA.

**Comment by dougbu** [comment]
Seems worth fixing the source file. That's not in this repo but we'll include an update in the next release.

**Comment by dougbu** [comment]
Update together w/ #377 in TFS

**Comment by dougbu** [comment]
It's the https://vstfdevdiv/DevDiv2/DevDiv/_versionControl?path=%24/DevDiv/Offcycle/WPT/WebStackRuntime/Main/src/Packages/content/NET_Library_EULA_ENU.txt file in TFS that needs to change for this issue

**Comment by dougbu** [comment]
Reassigned to @wtgodbe and @mkArtakMSFT

**Comment by mkArtakMSFT** [comment]
This was fixed as part of https://vstfdevdiv/DevDiv2/DevDiv/_versionControl/changeset/1776742/
