### ISSUE TITLE
Broken link to GDPR commitment in EULA

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [aspnet/AspNetWebStack#377]
### Title
Paragraph 4.b. (Processing of Personal Data) of the NuGet package EULA includes a broken link.

### Functional impact
No

### Minimal repro steps
1. Open <https://www.nuget.org/packages/Microsoft.AspNet.WebApi/5.2.9/License> in a Web browser.
2. See paragraph 4.b.:
   ```
   b.	Processing of Personal Data. To the extent Microsoft is a processor or subprocessor of
   personal data in connection with the software, Microsoft makes the commitments in the
   European Union General Data Protection Regulation Terms of the Online Services Terms to all
   customers effective May 25, 2018, at http://go.microsoft.com/?linkid=9840733.
   ```
3. Try to open the <http://go.microsoft.com/?linkid=9840733> link.

### Expected result
The link should redirect to the Online Services Terms or to <https://docs.microsoft.com/en-us/legal/gdpr>.

### Actual result
The link redirects to <https://www.bing.com/?ref=go&linkid=9840733>, which is a Bing search page.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@ChrisSfanos do you know what this link `http://go.microsoft.com/?linkid=9840733` should point to?

**Comment by dougbu** [comment]
@ChrisSfanos do you have access to update the go.microsoft.com link? Doing so would avoid having to update our files in a separate step.

If not, @mkArtakMSFT please create a new aka.ms link (or whatever) linking to <https://docs.microsoft.com/legal/gdpr>. I can update the files as necessary.

Either way, note the new link should _not_ have `en-us` or any other language code in it. https://docs.microsoft.com/legal/gdpr redirects based on users' configurations.

**Comment by mkArtakMSFT** [comment]
Here you go, @dougbu: https://aka.ms/aspnet/gdpr

**Comment by dougbu** [comment]
Update together w/ #376 in TFS

**Comment by ChrisSfanos** [comment]
It doesn't look like I have access to that old link - sorry

**Comment by dougbu** [comment]
It's the various HTM and TXT files under https://vstfdevdiv/DevDiv2/DevDiv/_versionControl?path=%24/DevDiv/Offcycle/WPT/WebStackRuntime/Main/src/Packages/content/ in TFS that need to change to use the new https://aka.ms/aspnet/gdpr link. Probably easiest to search 'n replace in VS Code (or whatever) after checking out all files in the folder for edit.

**Comment by dougbu** [comment]
Reassigned to you two, @mkArtakMSFT and @wtgodbe

**Comment by mkArtakMSFT** [comment]
@wtgodbe @halter73 can you guys please review this: http://codeflow/extensions/launcher.html?server=https%3a%2f%2fdevdiv.visualstudio.com%2f&projectId=2cf24b7e-a928-45ce-a6a9-464648313e80&reviewId=468512&projectshortname=zCodeFlowConfigs

**Comment by mkArtakMSFT** [comment]
Thanks @halter73.
Fix is now merged and will be included in the upcoming release: https://vstfdevdiv/DevDiv2/DevDiv/_versionControl/changeset/1776742/
