### ISSUE TITLE
CopyToAsync to a PushStreamContent hangs for an ASP.NET app running inside the container

### ISSUE THREAD

**Issue by chunye** [aspnet/AspNetWebStack#385]
This issue is reported by a customer when running their ASP.NET app inside a Windows Hyper-V container, an Azure Web App offering. The issue doesn't repro when the app runs outside the container, or with only 1 single download.

The error happens when we do multiple downloads (~2000 total) with 50 of them running in parallel against the server app. The following call from the client returns an error "Error while copying content to a stream".

                var httpResponseMessage = await httpClient.GetAsync(url);

Here is the related server code in question:

Code that hangs after multiple downloads:
 
        [Route("direct")]
        [HttpGet]
        public HttpResponseMessage GetDownload()
        {
            var fullResponse = Request.CreateResponse(HttpStatusCode.OK);
            var mappedFilePath = GetMappedFilePath();
 
            fullResponse.Content = new PushStreamContent(async (s, t, c) =>
            {
                FileStream stream = default;
                try
                {
                    stream = File.OpenRead(mappedFilePath);
                    await stream.CopyToAsync(s);
                }
                finally
                {
                    stream?.Close();
                    s.Close();
                }
            });
 
            fullResponse.Content.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
            fullResponse.Content.Headers.ContentDisposition =
                new ContentDispositionHeaderValue("attachment")
                {
                    FileName = Uri.EscapeDataString(FileName)
                };
 
            return fullResponse;
        }

Code that works w/o issues:

        [Route("direct")]
        [HttpGet]
        public HttpResponseMessage GetDownload()
        {
            var fullResponse = Request.CreateResponse(HttpStatusCode.OK);
            var mappedFilePath = GetMappedFilePath();
 
            fullResponse.Content = new StreamContent(File.OpenRead(mappedFilePath)); // This works.
            fullResponse.Content.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
            fullResponse.Content.Headers.ContentDisposition =
                new ContentDispositionHeaderValue("attachment")
                {
                    FileName = Uri.EscapeDataString(FileName)
                };
 
            return fullResponse;
        }

In the error case, the following call throws an exception. From the network capture, this looks like the client does a TCP reset after it is timed out.  Using a StreamContent avoids this exception.
 
                    await stream.CopyToAsync(s);

Here is the exception:

********** 2/6/2023 7:23:15 AM **********
Inner Exception Type: System.Runtime.InteropServices.COMException
Inner Exception: The I/O operation has been aborted because of either a thread exit or an application request. (Exception from HRESULT: 0x800703E3)
Inner Source: 
Exception Type: System.Web.HttpException
Exception: An error occurred while communicating with the remote host. The error code is 0x800703E3.
Source: System.Web
Stack Trace: 
   at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
   at System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush()
   at System.Web.HttpResponse.Flush(Boolean finalFlush, Boolean async)
   at System.Web.HttpWriter.WriteFromStream(Byte[] data, Int32 offset, Int32 size)
   at System.IO.Stream.<>c.<BeginWriteInternal>b__46_0(Object <p0>)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.Stream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at CoreIssuesTest.Controllers.DownloadController.<>c__DisplayClass2_0.<<GetDownload>b__0>d.MoveNext()

Customer wants to know why their app doesn't work when running inside the container. Please contact me if needed for a repro or client and server code.

**Comment by chunye** [comment]
The app was targeting .NET Framework 4.8 and below are the package versions.

This is the package.config.

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Antlr" version="3.5.0.2" targetFramework="net48" />
  <package id="Autofac" version="6.5.0" targetFramework="net48" />
  <package id="Autofac.Owin" version="7.0.0" targetFramework="net48" />
  <package id="Autofac.WebApi2" version="6.1.1" targetFramework="net48" />
  <package id="Autofac.WebApi2.Owin" version="6.1.0" targetFramework="net48" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.9" targetFramework="net48" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.9" targetFramework="net48" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.9" targetFramework="net48" />
  <package id="Microsoft.AspNet.WebApi.Owin" version="5.2.9" targetFramework="net48" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.9" targetFramework="net48" />
  <package id="Microsoft.Bcl.AsyncInterfaces" version="7.0.0" targetFramework="net48" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="3.6.0" targetFramework="net48" />
  <package id="Microsoft.Owin" version="4.2.2" targetFramework="net48" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="4.2.2" targetFramework="net48" />
  <package id="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" version="1.17.0" targetFramework="net48" />
  <package id="Microsoft.Web.Infrastructure" version="2.0.1" targetFramework="net48" />
  <package id="Newtonsoft.Json" version="13.0.2" targetFramework="net48" />
  <package id="Owin" version="1.0" targetFramework="net48" />
  <package id="System.Buffers" version="4.5.1" targetFramework="net48" />
  <package id="System.Diagnostics.DiagnosticSource" version="7.0.0" targetFramework="net48" />
  <package id="System.IO" version="4.3.0" targetFramework="net48" />
  <package id="System.IO.Hashing" version="7.0.0" targetFramework="net48" />
  <package id="System.Memory" version="4.5.5" targetFramework="net48" />
  <package id="System.Memory.Data" version="7.0.0" targetFramework="net48" />
  <package id="System.Net.Http" version="4.3.4" targetFramework="net48" />
  <package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net48" />
  <package id="System.Runtime" version="4.3.1" targetFramework="net48" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="6.0.0" targetFramework="net48" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net48" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.1" targetFramework="net48" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net48" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net48" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.2" targetFramework="net48" />
  <package id="System.Text.Encodings.Web" version="7.0.0" targetFramework="net48" />
  <package id="System.Text.Json" version="7.0.0" targetFramework="net48" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.4" targetFramework="net48" />
  <package id="System.ValueTuple" version="4.5.0" targetFramework="net48" />
</packages>

**Comment by chunye** [comment]
<packages>
  <package id="Antlr" version="3.5.0.2" targetFramework="net48" />
  <package id="Autofac" version="6.5.0" targetFramework="net48" />
  <package id="Autofac.Owin" version="7.0.0" targetFramework="net48" />
  <package id="Autofac.WebApi2" version="6.1.1" targetFramework="net48" />
  <package id="Autofac.WebApi2.Owin" version="6.1.0" targetFramework="net48" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.9" targetFramework="net48" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.9" targetFramework="net48" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.9" targetFramework="net48" />
  <package id="Microsoft.AspNet.WebApi.Owin" version="5.2.9" targetFramework="net48" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.9" targetFramework="net48" />
  <package id="Microsoft.Bcl.AsyncInterfaces" version="7.0.0" targetFramework="net48" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="3.6.0" targetFramework="net48" />
  <package id="Microsoft.Owin" version="4.2.2" targetFramework="net48" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="4.2.2" targetFramework="net48" />
  <package id="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" version="1.17.0" targetFramework="net48" />
  <package id="Microsoft.Web.Infrastructure" version="2.0.1" targetFramework="net48" />
  <package id="Newtonsoft.Json" version="13.0.2" targetFramework="net48" />
  <package id="Owin" version="1.0" targetFramework="net48" />
  <package id="System.Buffers" version="4.5.1" targetFramework="net48" />
  <package id="System.Diagnostics.DiagnosticSource" version="7.0.0" targetFramework="net48" />
  <package id="System.IO" version="4.3.0" targetFramework="net48" />
  <package id="System.IO.Hashing" version="7.0.0" targetFramework="net48" />
  <package id="System.Memory" version="4.5.5" targetFramework="net48" />
  <package id="System.Memory.Data" version="7.0.0" targetFramework="net48" />
  <package id="System.Net.Http" version="4.3.4" targetFramework="net48" />
  <package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net48" />
  <package id="System.Runtime" version="4.3.1" targetFramework="net48" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="6.0.0" targetFramework="net48" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net48" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.1" targetFramework="net48" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net48" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net48" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.2" targetFramework="net48" />
  <package id="System.Text.Encodings.Web" version="7.0.0" targetFramework="net48" />
  <package id="System.Text.Json" version="7.0.0" targetFramework="net48" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.4" targetFramework="net48" />
  <package id="System.ValueTuple" version="4.5.0" targetFramework="net48" />
</packages>

**Comment by Tratcher** [comment]
- How large are the downloads?
- Does the client actively consume the download data? Some stress clients don't process responses like a normal client.
- Does the CPU and network remain saturated during the test?
- Why use PushStreamContent when StreamContent is adequate?

**Comment by chunye** [comment]
How large are the downloads?
10mb for each download. 
10,598,744 test.docx

Does the client actively consume the download data? Some stress clients don't process responses like a normal client.
I think so. It is CX's code so I can gurantee it is not buggy. If you have access to this ICM https://portal.microsofticm.com/imp/v3/incidents/details/357641952/home, you can download both client and server code there.

Does the CPU and network remain saturated during the test?
CPU is near 100% during test.

Why use PushStreamContent when StreamContent is adequate?
Question for CX. The app is for testing only. I assume their real app (also hitting the same issue in production) has a need to use PushStreamContent.

**Comment by Tratcher** [comment]
Also, remove `s.Close();`, closing the output stream is the servers responsibility. The exception should make it close abortively so the client is aware of the failure.

**Comment by chunye** [comment]
"closing the output stream is the servers responsibility" - do you mean client?  I tried removing "s.Close()" but w/o change on the client side, the download doesn't finish

BTW, can we add someone else to this thread to comment?  I didn't write the code initially.

**Comment by Tratcher** [comment]
> BTW, can we add someone else to this thread to comment?

This is public, go ahead.

> Also, remove `s.Close();`, closing the output stream is the servers responsibility. The exception should make it close abortively so the client is aware of the failure.

@dougbu can you confirm this? I'd have expected the WebApi infrastructure to close the response stream after PushStreamContent finished, or to abort it if there was an exception thrown.

**Comment by dougbu** [comment]
> > Also, remove `s.Close();`, closing the output stream is the servers responsibility. The exception should make it close abortively so the client is aware of the failure.
> 
> @dougbu can you confirm this? I'd have expected the WebApi infrastructure to close the response stream after PushStreamContent finished, or to abort it if there was an exception thrown.

The call to `HttpContent.SerializeToStreamAsync(...)` is _not_ in this repo. `HttpContent` calls `SerializeToStreamAsync(...)` [w/in `CopyToAsync(...)`](https://github.com/microsoft/referencesource/blob/master/System/net/System/Net/Http/HttpContent.cs#L223) (in which case the `Stream` is owned by the caller and [when buffering its content](https://github.com/microsoft/referencesource/blob/master/System/net/System/Net/Http/HttpContent.cs#L311) (in which case the buffered `MemoryStream` is disposed when the `HttpContent` is).

**Comment by chunye** [comment]
@dougbu Based on what I am reading, the code is still correct right?

**Comment by dougbu** [comment]
@chunye I'm not sure how best to use `PushStreamContent` but would say the `StreamContent` code in the description is significantly more straightforward.

Unfortunately, much of the historical context about choices in this repo has been lost. Perhaps the following samples could help:
- https://github.com/aspnet/samples/tree/main/samples/aspnet/WebApi/PushContentControllerSample
- https://github.com/aspnet/samples/tree/main/samples/aspnet/WebApi/UploadXDocumentSample
