### ISSUE TITLE
Add netstandard support to appropriate packages

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetWebStack#4]
The Web API "client" packages should have support for the lowest netstandard TFM possible.

**Comment by Tratcher** [comment]
why hasn't this shipped to nuget.org yet?

**Comment by CIPop** [comment]
/cc: @jasmineymlo @tameraw 
@Eilon This is internally required for Azure IoT SDK. Any ETA on getting an RTM NuGet version for NetStandard 1.1?

**Comment by YakhontovYaroslav** [comment]
@Eilon @dougbu 
I`ve just checked out latest .Client build here https://dotnet.myget.org/feed/aspnetwebstack-dev/package/nuget/Microsoft.AspNet.WebApi.Client and it seems to miss some old functionality. For example FormUrlEncodedMediaTypeFormatter is gone. Is it intended change and what are the replacements? 
I`m using this formatter (as well as all other formatters from this assembly) for building dynamic client implementations with help of Castle.Core package. 
Upgrading to this build version release will introduce many breaking changes for many users.

**Comment by dougbu** [comment]
@YakhontovYaroslav the `FormUrlEncodedMediaTypeFormatter` class is a server-side i.e. input formatter and has never been included in `Microsoft.AspNet.WebApi.Client`. Are you looking for the `Microsoft.AspNet.WebApi` package?

More generally, if you're building an ASP.NET Core web application, please have a look at `Microsoft.AspNetCore.Mvc` and the packages it depends on. `FormUrlEncodedMediaTypeFormatter` does not exist in that framework because ASP.NET Core MVC model binds form-URL requests without input formatters.

**Comment by YakhontovYaroslav** [comment]
It was definitely in https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/ nuget.
I`m talking about https://github.com/aspnet/AspNetWebStack/blob/master/src/System.Net.Http.Formatting/Formatting/FormUrlEncodedMediaTypeFormatter.cs this class. It`s included in https://github.com/aspnet/AspNetWebStack/tree/master/src/System.Net.Http.Formatting , but missing from https://github.com/aspnet/AspNetWebStack/tree/master/src/System.Net.Http.Formatting.NetStandard an Core versions. 

Im not looking for server side implementation. As i mentioned above, we are using this formatter (as well as Json and Xml from same namespace) to dynamically build HttpClient pipelines using DelegatingHandler and Castle.Core proxies. Its neat way to declare whole serialization\deserialization pipelines using just interface declaration with custom attributes like ContentType, Accept, Route, Method etc. Many 3rd party APIs still uses FormUrlEncoded in POST and GET requests, and we must somehow integrate with them.

Code Example of such interface:
`

    [RestContract("http://example.com/api", timeout: 180)]
    public interface IExampleApiClient
    {
        [RestMethod("/v2/login", RestMethod.Post)]
        [Accept("text\xml")]
        [ContenType("application\json")]
        Task<LoginResult> LoginAsync(LoginModel model, [Header("HeaderName")] headerValue);
    }

`
