### ISSUE TITLE
Release for 5.2.9

### ISSUE THREAD

**Issue by grunci** [aspnet/AspNetWebStack#403]
Hi,
I am looking for the official release for Microsoft.AspNet.WebApi.Core 5.2.9
According to https://nuget.info/packages/Microsoft.AspNet.WebApi.Core/5.2.9 this is the repo where I can find the source code.
Could someone please help me out?

**Comment by CZEMacLeod** [comment]
@grunci The 5.2.9 releases are tagged with 3.2.9 as the major version numbers are different between different libraries in this repo, but the minor/release numbers are kept in sync.

The source code is available in the [releases](https://github.com/aspnet/AspNetWebStack/releases/tag/v3.2.9) section of the repo (and is tagged [v3.2.9](https://github.com/aspnet/AspNetWebStack/tree/v3.2.9))
The `Microsoft.AspNet.WebApi.Core` package contains the assembly `System.Web.Http`, the source of which is in [src/System.Web.Http](https://github.com/aspnet/AspNetWebStack/tree/main/src/System.Web.Http)
The official binary releases are on nuget.org at https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Core/5.2.9

If I have anything wrong here, hopefully one of the maintainers will jump in and correct me.

Hope this helps.

**Comment by grunci** [comment]
Hi @CZEMacLeod ,
Thanks a lot for the explanation.

Regards,
Grunci
