### ISSUE TITLE
Question of  WebApi  and Owin on IIS

### ISSUE THREAD

**Issue by John0King** [aspnet/AspNetWebStack#410]
there are many package on nuget for hosting webapi:

- Microsoft.AspNet.WebApi.WebHost
- Microsoft.AspNet.WebApi.Owin
- Microsoft.AspNet.WebApi.OwinSelfHost
- Microsoft.AspNet.WebApi.SelfHost

and now in Visual Studio ,  it seem only use `Microsoft.AspNet.WebApi.WebHost`  
and there no document  on `learn.microsoft.com`  about `webapi` + `owin` + `IIS`, thats why I ask here.

`Microsoft.AspNet.WebApi.WebHost`  it saids it's support owin,  but how does it work ? and where's the position of `Microsoft.AspNet.WebApi.Owin` ?

I run a owin middleware to set a static `AsyncLocal<T>` value and find out that   this middleware's  `AsyncLocal<T>`  is been "cleaned"  when the code runs into  webapi  controller,  the only situation I think about is that  the owin middleware is running different async flow than webapi.  
and I wonder that does webapi controller actully runs inside the owin piepline .
 I indeed put the `app.UseWebApi(config)` inside `Startup.Configuration()`  (witch means it use `Microsoft.AspNet.WebApi.Owin`), and the  `Microsoft.AspNet.WebApi.WebHost`  is also installed.

**Comment by mkArtakMSFT** [comment]
@Tratcher can you look into this one, please? Thanks!

**Comment by Tratcher** [comment]
WebApi has the following hosting options:
- WebApi -> IIS (System.Web.Http.WebHost)
- WebApi -> WCF -> HttpListener (System.Web.Http.SelfHost)
- WebApi -> Owin -> IIS or HttpListener (System.Web.Http.Owin)

When running on IIS the only reason to include Owin is if you also have other Owin components/middleware that you need to interop with.

If you really want to do that then:
- Remove System.Web.Http.WebHost so IIS doesn't start WebApi directly.
- Add System.Web.Http.Owin
- Add Microsoft.Owin.Host.SystemWeb
- Use the Startup.cs from the owin self-host docs: https://learn.microsoft.com/en-us/aspnet/web-api/overview/hosting-aspnet-web-api/use-owin-to-self-host-web-api#configure-web-api-for-self-host (Program.cs is not required).

**Comment by John0King** [comment]
@Tratcher   
I'm doing a very simple test  and here is the result 


###  1. OwinMiddleare + [ MVC ] or [ WebApi with WebHost ]
```jsonc
//MVC
{
    "From": "Mvc",
    "State": "ExecuteRequestHandler",
    "httpCtx": {
        "Value": 2
    },
    "AsyncLocalCtx": null
}
```

```jsonc
//webapi
{
    "from": "WebApi",
    "State": "ExecuteRequestHandler",
    "httpCtx": {
        "Value": 2
    },
    "asyncLocalCtx": null
}
```

### 2. OwinMiddleware + [Owin  WebApi]

```jsonc
//webapi

{
    "from": "WebApi",
    "State": "PreExecuteRequestHandler",
    "httpCtx": {
        "Value": 2
    },
    "asyncLocalCtx": {
        "Value": 2
    }
}

```

but  when I use StateMarker to make my  initializeMiddleare  run earlier 

```jsonc
//   initializeMdilleare run in [PipelineStage.Authenticate]
// and webapi runs in  [PipelineStage.Authorize]
{
    "from": "WebApi",
    "State": "AuthorizeRequest",
    "httpCtx": {
        "Value": 2
    },
    "asyncLocalCtx": null
}
```


from the result , it seems   that the owin middleare runs in different stage that have different async flow ,  
and I'm wonder is there a solution to fix it ?

**Comment by Tratcher** [comment]
IIS/System.Web's integrated pipeline is quite complex, especially for async components. Yes, the Owin components aren't great about transferring async state between pipeline stages and I'm not aware of an easy fix for that. My general recommendation is not to rely on async state, store any request specific information in HttpContext, like in Items, so it automatically flows with the request without relying on any implicit thread state.
