### ISSUE TITLE
[HttpMessageContent] Invalid Server header when multiple values are present

### ISSUE THREAD

**Issue by manandre** [aspnet/AspNetWebStack#411]
When serializing the `Server` header, the comma `,` separator is used while the [RFC 9110](https://datatracker.ietf.org/doc/html/rfc9110#name-server) states that the space ` ` seaprator should be used, like for the `User-Agent` header.
It is also correctly stated and implemented in .NET [runtime](https://github.com/dotnet/runtime/blob/ffa4ef75ec135a64a30e14df5c2afca340ee1203/src/libraries/System.Net.Http/src/System/Net/Http/Headers/ProductInfoHeaderParser.cs#L13)

### How to reproduce the issue
```cs
using System.Net;

var httpResponseMessage = new HttpResponseMessage(HttpStatusCode.OK);
httpResponseMessage.Headers.Add("Server", new[] {"My", "Gateway"});
var message = new HttpMessageContent(httpResponseMessage);
var messageString = await message.ReadAsStringAsync();
Console.WriteLine(messageString);
```
### Obtained result
```
HTTP/1.1 200 OK
Server: My, Gateway
```
### Expected result
```
HTTP/1.1 200 OK
Server: My Gateway
```
### Fix proposal
Add the `Server` header to the existing list of [`_spaceSeparatedValueHeaderFields`](https://github.com/aspnet/AspNetWebStack/blob/1231b77d79956152831b75ad7f094f844251b97f/src/System.Net.Http.Formatting/HttpMessageContent.cs#L46)
https://github.com/aspnet/AspNetWebStack/blob/1231b77d79956152831b75ad7f094f844251b97f/src/System.Net.Http.Formatting/HttpMessageContent.cs#L45-L49

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're not making any improvements in this area any more as this project is in maintenance mode. Only critical blocking issue with wide impact and security issues are considered.
