### ISSUE TITLE
AddVersionedApiExplorer not working in Asp.Versioning?

### ISSUE THREAD

**Issue by Philxm** [aspnet/AspNetWebStack#413]
Hi, 

I have installed
> 1. Asp.Versioning.Mvc
> 2. Asp.Versioning.Mvc.ApiExplorer,

Also, I am using the following at the beginning of the code:
```
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Asp.Versioning;
using Asp.Versioning.ApiExplorer;
using Microsoft.OpenApi.Models;

```
However, it still shows Compiler Error CS1061 on AddVersionedApiExplorer below,

![}Q)MC00WCA5~LEDCRJNKR27](https://github.com/aspnet/AspNetWebStack/assets/161403452/b5411375-7e14-4fef-ba5d-527e127ae3ee)

Can you help with any solution?

Thanks,

Phil

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. The issue that you're observing is not related to this repo.
What seems to be happening here is the method is not found. So perhaps you're referencing a wrong method or missed to reference the correct assembly / namespace, where it's defined.
