### ISSUE TITLE
Can't install SSMS and getting error The type initializer for 'PerTypeValues`1' threw an exception

### ISSUE THREAD

**Issue by Philxm** [aspnet/AspNetWebStack#414]
Hi,

I want to install SSMS, but failed. It shows below error information.

It is the VSIX Installer issue and says "The type initializer for 'PerTypeValues`1' threw an exception"
 
![FRNBFJ _U@ECC81Z6}_$)B7](https://github.com/aspnet/AspNetWebStack/assets/161403452/335023d5-04d0-4f76-af00-853ed7854c01)

Can anyone advise the solution?

Many thanks,

Phil

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This repo has nothing to do with the SSMS installer. We recommend reporting this via https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0
