### ISSUE TITLE
Support for params keyword

### ISSUE THREAD

**Issue by crystalcode-io** [aspnet/AspNetWebStack#49]
I was surprised to see that `params` was not supported by Web API actions.

```csharp
[HttpPost]
[Route("ParamsTest")]
public String[] Test([FromBody] params String[] values)
{
    return values;
}
```

### Test 1
```
POST / HTTP/1.1
["a","b","c"]
```
The above request responds with:
```json
["a","b","c"]
```

### Test 2
```
POST / HTTP/1.1
"a"
```
The above request responds with:
```json
null
```
However, I expected:
```json
["a"]
```
### Conclusion
It would be great if the binder could respect the `params` modifier, thus enabling endpoints to accept one-or-many of a given parameter.

For the sake of completeness, passing around non-primitive objects:

```csharp
[HttpPost]
[Route("Customers")]
public void Test([FromBody] params Customer[] customers)
{
    // do important stuff
}
```
Would accept:
```
POST / HTTP/1.1
{"Name":"Alice"}
```
And as well, it would accept:
```
POST / HTTP/1.1
[{"Name":"Alice"},{"Name":"Bob"},{"Name":"Carol"}]
```

**Comment by crystalcode-io** [comment]
For those interested, I've posted up at SO: http://stackoverflow.com/q/43957028/409279.

**Comment by Eilon** [comment]
The `params` keyword is mostly just a hint to the C# (and other) compilers to *hide* the creating of the array when passing in a non-array value.

If you have this method:

```c#
public void DoStuff(params int[] a);
```

... and call it with `DoStuff(1, 2, 3)`, the C# compiler will generate the code as `DoStuff(new int[] { 1, 2, 3 })`.

As such, the method really always takes in an array, so an array of data must be passed in.

The same is true with Web API: if the method takes in an array, it will work only if you pass in an array.

On the SO post there are some tricks/alternatives, but we have no plans of adding built-in support for this in Web API.
