### ISSUE TITLE
Support for mixed-mode authentication

### ISSUE THREAD

**Issue by arc95** [aspnet/AspNetWebStack#53]
Hi. We're building an ASP.NET MVC 5 app in Visual Studio and have used the great library [OWIN-MixedAuth](https://github.com/MohammadYounes/OWIN-MixedAuth) to add mixed-mode authentication: to allow both Windows and Forms auth in one app. This way our intranet and external users can use the same app, being authenticated against the Identity Library and its associated tables on SQL Server.

We'd like to request the addition of this library to future versions of MVC/MVC Core. We've found it to be solid with great support. And many enterprises need mixed authentication. This solution is solid and secure. 

Thanks.

**Comment by dougbu** [comment]
Thank you for your feature request. We have no plans to add this dependency in a future release.
