### ISSUE TITLE
API endpoint only accepts GET when it should accept POST

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetWebStack#55]
_From @yongjp94 on August 8, 2017 17:57_

Upon days of investigation and posting on online forums, I feel that this may be a bug.
I have attached a link to a stackoverflow question that I posted regarding this problem.

https://stackoverflow.com/questions/45553296/api-endpoint-only-allows-get-when-it-should-take-post

Thank you.

_Copied from original issue: aspnet/Mvc#6636_

**Comment by Eilon** [comment]
_From @pranavkm on August 8, 2017 18:43_

Seems like this was an issue with Web API 2.0 (and not Asp.Net Core Mvc). If so, https://github.com/aspnet/aspnetwebstack would be the right place to file this issue.

**Comment by dougbu** [comment]
Clearing milestone because we haven't investigated

**Comment by dougbu** [comment]
We suspect this issue relates to a misconfiguration of IIS. If you're still hitting this issue and can provide more information than what's in the StackOverflow discussion (which is confused by multiple edits), please create a new issue. Include steps to reproduce in addition to the symptoms.
