### ISSUE TITLE
Asp.Net MVC 5 app not working after VS 15.2 update to 15.3

### ISSUE THREAD

**Issue by MaximRouiller** [aspnet/AspNetWebStack#57]
*Issue moved from https://github.com/aspnet/Mvc/issues/6666 by @alfeg*

--------

After updating VS 15.2 to Vs 15.3 I were blocked with an issue.

Asp.net app suddenly report that it cannot load some assemblies

> Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

If I build same project with 15.2 version - everything works perfectly

I've pushed project with repro: https://github.com/alfeg/vs15_3repro

Steps:

* Build project with VS 15.2.
-- Ctrl+F5 on REPRO.UI.Headquarters web project.
-- Should open page with Hello World
* Build same project with VS 15.3
-- Ctrl+F5 on REPRO.UI.Headquarters web project.
-- Could not load file or assembly ... message appear

I've try to change some binding redirects, but has no luck, and this breaks build with 15.2 studio.

Any idea how to resolve, or where I should report this issue?

-----

**Comment by EIDIVANDI** [comment]
do you use any modul of enterpriseliberary .?

if yes try removing (if existes ) and reinstalling

**Comment by Eilon** [comment]
@pranavkm - any ideas?

**Comment by pranavkm** [comment]
@MaximRouiller once you build you get a bunch of warnings about adding bindings redirects. If you double click them, VS will auto update your web.config for you. That gets you past the first issue. The second issue you hit is https://github.com/dotnet/corefx/issues/23229. I'm investigating the other one, but doing a clean \ rebuild should get you past it.

**Comment by pranavkm** [comment]
Closing this one since we figured out a solution to the primary issue. We'll use the other one to track further work.
