### ISSUE TITLE
MediaTypeFormatter in the request CultureInfo

### ISSUE THREAD

**Issue by MehdyKarimpour** [aspnet/AspNetWebStack#59]
Hi guys, 

I have registered custom `JsonConverters` in the default `SerializerSettings` of the `JsonFormatter`, but one of them requires to send the result of evaluating `ToString` in the request `CultureInfo`. 

Unfortunately at some of the `async` jumps in the request pipeline (I suppose) the culture gets set back to en-US. The `JsonSerializer`´s Culture on the other side uses Invariant Culture. 

I've tried writing my own  `MediaTypeFormatter` but, while the request Culture is present in `CanWriteType`, by the time `WriteToStreamAsync` is called the Culture is set back to en-US. 

Just to note, I'm setting the culture in my own `IAuthorizationFilter` in the method `ExecuteAuthorizationFilterAsync` just before calling `continuation()`.

Is there any way to run MediaFormatters in the request culture? I'm considering moving to .Net Core. Could this problem have an easier solution there?  

Thanks a lot

**Comment by dougbu** [comment]
Thank you for contacting us. To evaluate whether this is indeed an issue in ASP.NET Web API, could you please elaborate on the scenario and provide us with a minimal repro project that illustrates the problem, preferably hosted in a GitHub repo?

## Details
Yes, in ASP.NET Core, `async` transitions should consistently carry the `CultureInfo` along.

In ASP.NET (non-Core), you may need to
- Move to a later version of the .NET Framework. .NET 4.6 introduced some `SynchronizationContext` improvements. What framework version were you using when you saw issues?
- Use the `SynchronizationContext` stored in `HttpRequestMessage.Properties`, assuming it's recent enough to include `CultureInfo`.
- Examine / fix any `ConfigureAwaiter(...)` calls in the application. `ConfigureAwaiter(...)` can change how information is carried as virtual threads are scheduled.

The other possibility is one of your dependencies has introduced a `SynchronizationContext` that does not carry `CultureInfo`.

**Comment by dougbu** [comment]
Thank you for your feedback. We're closing this issue as no updates have been provided and we have been unable to reproduce the issue. If you have more details and are encountering this issue please add a new reply and re-open the issue.
