### ISSUE TITLE
MVC5: Asynchronous child actions Not supported

### ISSUE THREAD

**Issue by sanilpaul** [aspnet/AspNetWebStack#61]
what is the recommended way to execute asynchronous actions (database access) through child actions in MVC5?  I understand its very subjective to what i do in the child action. In my case, its only async queries to sql server using EF6. 

Is wrapping in a task.run has any side effects in this case or is there any better way microsoft recommends other than changing to Synchronous? 
```csharp
@Html.Action("SampleChildAction)

public PartialViewResult SampleChildAction()
{
    Task.Run(async () => { await asyncMethod(); }).Result; 
    return PartialView("_SampleChildActionView");
}
```
I couldn't locate anything guidance from microsoft. I would appreciate any help.  
https://justsimplycode.com/2016/09/04/child-action-in-mvc-5-does-not-support-async/
https://github.com/aspnet/Home/issues/343

**Comment by Eilon** [comment]
Unfortunately I'm not aware of any good/clean way to do this. It's a limitation of how Child Actions are implemented in MVC, which I don't think there's a good way to work around.

**Comment by alohaninja** [comment]
`PartialViewResult` is single-threaded so you can't benefit from async - in fact it blocks the app from executing entirely. Here are some options we use to work around it - keep in mind it still executes your child actions synchronously...

### Using SynchronizationContext
``` 
private T InvokeAsyncMethod<T>(Func<Task<T>> func)
{
    var syncContext = SynchronizationContext.Current;
    SynchronizationContext.SetSynchronizationContext(null);

    var result = func.GetResult();

    SynchronizationContext.SetSynchronizationContext(syncContext);

    return result;
}
```

### Using Task Library
```
private T InvokeAsyncMethod<T>(Func<Task<T>> func)
{
    return Task.Factory.StartNew(func)
        .Unwrap()
        .GetAwaiter()
        .GetResult();
}
```

To use this approach - just call your async method inline...

`var user = InvokeAsyncMethod(() => user.getAsync(userId));
`

**Comment by benmccallum** [comment]
Dude, best timing for an answer here. Had this issue just yesterday. Thanks @alohaninja !

**Comment by benmccallum** [comment]
Unfortunately my async is never coming to completion with the Task library approach. Trying the SyncContext approach now, I think there's a type though. Should it be `var result = func().GetAwaiter().GetResult()`? I've tried setting `ConfigureAwait(false)` in my nuget package that is consumed by MV5 app, but no lucl thus far. Sigh.

**Comment by alohaninja** [comment]
> I think there's a typo in the first approach. Should it be `var result = func().GetAwaiter().GetResult()`?

Corrected - nice catch! 🎉
