### ISSUE TITLE
System.Web.Http - Unhandled use-case with AsyncLocal and Disposing

### ISSUE THREAD

**Issue by brandondahler** [aspnet/AspNetWebStack#75]
# Problem
In instances of `System.Web.Http.ApiController`, an AsyncLocal value that is set in the constructor is not preserved through to the Dispose method.

## Technical Info
When instances of `IHttpController` are instantiated, they are instantiated into the `ExecutionContext` of the `System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsync` method.

 Instead of being disposed within `SendAsync`, the disposal is delayed until  	`System.Web.Http.WebHost.HttpControllerHandler.ProcessRequestAsyncCore` (or other similar depending on hosting type) calls `System.Net.Http.HttpRequestMessageExtensions.DisposeRequestResources`.  This disposal is registered by `System.Web.Http.ApiController` in `ExecuteAsync`.  

Because `DisposeRequestResources` is called from an `ExecutionContext` that is not the or a child of the `ExecutionContext` that the `IHttpController` was instantiated in, any values stored in an AsyncLocal in the constructor are no longer available in the Dispose method.

# Example Code
Below is a trivial implementation that shows the issue.
``` C#

public class ExampleController 
    : ApiController
{
    private static readonly AsyncLocal<string> _asyncLocal = new AsyncLocal<string>();

    public ExampleController ()
    {
        _asyncLocal.Value = "Test";
    }

    public void Get()
    {
        // _asyncLocal.Value
        // Expected value: "Test"
        // Actual value: "Test"

        // Does not throw, _asyncLocal.Value == "Test"
        if (_asyncLocal.Value != "Test")
            throw new InvalidOperationException();
    }



    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        // _asyncLocal.Value
        // Expected value: "Test"
        // Actual value: null

        // Throws, _asyncLocal.Value == null.
        if (_asyncLocal.Value != "Test")
            throw new InvalidOperationException();
    }
}
```

## Expected Output
No exception occurs

## Actual Output
InvalidOperationException thrown by void Dispose(bool disposing).

# Use Case
Going outside of the trivial example, one use-case for the desired behavior is when using AsyncLocal values to implicitly flow context into library or otherwise context-unaware code while having that context start at controller instantiation and persisting until controller disposal.

Below is some slightly less trivial code that displays the basics of this use-case:
``` C#
public class ExampleContext
    : IDisposable
{
    public string ContextValue { get; }

    public static ExampleContext Current
    {
        get => CurrentStack.Peek();
        set => CurrentStack = CurrentStack.Push(value);
    }

    private static IImmutableStack<ExampleContext> CurrentStack
    {
        get => _currentAsyncLocal.Value ?? ImmutableStack<ExampleContext>.Empty;
        set => _currentAsyncLocal.Value = value;
    }

    private static readonly AsyncLocal<IImmutableStack<ExampleContext>> _currentAsyncLocal = new AsyncLocal<IImmutableStack<ExampleContext>>();


    public ExampleContext(string contextValue)
    {
        ContextValue = contextValue;

        Current = this;
    }

    public void Dispose()
    {
        // Throws
        Debug.Assert(!CurrentStack.IsEmpty);
        Debug.Assert(Current == this);

        CurrentStack = CurrentStack.Pop();
    }
}

public class ExampleController
    : ApiController
{
    private readonly ExampleContext _exampleContext;


    public ExampleController()
    {
        _exampleContext = new ExampleContext("Testing");
    }

    public async Task Get()
    {
        // "Testing"
        Debug.WriteLine(_exampleContext.ContextValue);

        // "Testing"
        ExampleLibrary.WriteContextValue();

        // "Testing"
        await ExampleLibrary.WriteContextValueAfterAsync();

        using (new ExampleContext("Nested Context"))
        {
            // "Testing"
            Debug.WriteLine(_exampleContext.ContextValue);

            // "Nested Context"
            ExampleLibrary.WriteContextValue();

            // "Nested Context"
            await ExampleLibrary.WriteContextValueAfterAsync();
        }

        // "Testing"
        Debug.WriteLine(_exampleContext.ContextValue);

        // "Testing"
        ExampleLibrary.WriteContextValue();

        // "Testing"
        await ExampleLibrary.WriteContextValueAfterAsync();
    }



    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        // Throws exception, ExampleContext.Current attempts to Peek() empty stack.
        _exampleContext.Dispose();
    }
}

public static class ExampleLibrary
{
    public static void WriteContextValue()
    {
        Debug.WriteLine(ExampleContext.Current.ContextValue);
    }


    public static async Task WriteContextValueAfterAsync()
    {
        await Task.Yield();

        WriteContextValue();

        await Task.Yield();
    }
}
```

## Discussion Point
Part of this use-case is based on the assumption that IDisposable types should generally be disposed within the same context as when they were instantiated.  Is this a correct or expected assumption? 

This assumption does hold true for MVC controllers.

# Solution
One way to solve this would be to not delay the disposal of IHttpController instances by try-casting it to a disposable and directly disposing it inside `System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsync` after awaitng the `HttpResponseMessage`.

# Work Around
It is possible to delay the instantiation and disposal of the context-specific type until ApiController's ExecuteAsync method by overriding ExecuteAsync and wrapping the awaited base call with the context-specific variable.

**Comment by rynowak** [comment]
Controllers are intentionally disposed as late as possible because they are visible in filters, and because things that write the response often need access to the controller's resources. This isn't really something we can change.

**Comment by davidfowl** [comment]
Thats' right this can't work if you set it in the constructor. You need to set it earlier in the async flow.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
