### ISSUE TITLE
Unhandled exception is being logged when client cancels requests still happens

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetWebStack#8]
Original bug: https://aspnetwebstack.codeplex.com/workitem/2283

---

> It appears this issue was clsoed for some reason.
> http://aspnetwebstack.codeplex.com/workitem/1797 
> 
> It still happens on 5.2.3 and I posted details back in April of the error it gives. I get these everyday. (I am not using the workaround listed as this was supposed to be fixed)

---

> I'm getting this too. In my case the Cancellation token is setup within the webapi controller method, and set to cancel after xx seconds. So, the webapi itself if cancelling the request if it's taking too long (we depend on downstream systems so cancel if they are not responding in time), not an external client.
> 
> When the cancellation token fires, the webapi call is cancelled but the global exception handler (implementation of IExceptionHandler) is not fired at all. We get a 500 and then an unhandled ASP.NET exception in the Even Log.
> 
> WebApi 5.2.3

---

> btw, the workaround listed (DelegatingHandler) doesn't work for me as the cancellation is happening from within the method itself after the delgating handler has been called

**Comment by thomaswurtz** [comment]
Hi, is there any due date on this?

**Comment by Eilon** [comment]
@thomaswurtz sorry not at this time. We are working on a few other releases for ASP.NET Core right now, then we will get back to working on the 5.2.4 release of ASP.NET (non-Core) MVC/Web API.

**Comment by cblaze22** [comment]
July 2018 now?

**Comment by IanKemp** [comment]
@cblaze22At this point we have to be happy with any scraps MS is willing to give us on old MVC.

**Comment by TSSchoof** [comment]
I really hope they will solve this eventually. It's a really annoying issue.

**Comment by 304NotModified** [comment]
Also looking for a fix.
