### ISSUE TITLE
DefaultBodyModelValidator extensibility

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetWebStack#9]
Original PR: https://aspnetwebstack.codeplex.com/SourceControl/network/forks/abatishchev/modelvalidation2/contribution/8644

---

> Opening DefaultBodyModelValidator for changes via inheritance and overriding of its private (now protected virtual) method.
> 
> As described in the following issue for Fluent Validation Web API integration package https://github.com/JeremySkinner/FluentValidation/issues/178#issuecomment-166586996, FV makes small changes in DFMV but has to copy-paste the whole class as-is because it's barely extendable having all method as private.
> 
> This pull request changes them to protected virtual with minimal related changes (few nested private methods should be now protected, one internal interface - public).
> 
> Please review!
> 
> MPSIT Engineering extensively uses ASP.NET Web API for current and new projects, and relies on Fluent Validation to validate input. But unfortunately we're unable to change some of the behaviors without copy-pasting huge pieces of code, what would be perfectly avoidable with the proposed change.
> 
> Thanks,
> Alex

**Comment by Eilon** [comment]
We should clean up the original PR a bit - we don't want public (incl. protected) nested types for this.

**Comment by dougbu** [comment]
eebbf388
